### ISSUE TITLE
Polish: Terms of Service button says "Deny". Maybe should be reworded to "Reject"

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#10]
The buttons are close to this header:

> Welcome to Scatter. Let's get started setting up your Scatter.

So it wasn't immediately obvious to me that Accept/Deny refers to the TOS below and not that header. Initially I thought I was able to skip onboarding here when clicking Deny.

![image](https://user-images.githubusercontent.com/2923/42550373-6092e92e-849f-11e8-9e48-c278658c1046.png)

**Comment by nsjames** [comment]
Done
