### ISSUE TITLE
Not formatting to correct precision for tokens (EOS)

### ISSUE THREAD

**Issue by Novusphere** [GetScatter/ScatterDesktop#109]
You're autoformatting to 4 decimal places before sending instead of the precision set to by the token contract, which means any token that doesn't have 4 decimal places breaks (the transfer fails).

You can test this with the token ATMOS (contract: novusphereio), which uses 3 decimal places. Send me an EOS account and I can send you a small amount to try with.

**Comment by nsjames** [comment]
4555c5de9b196713dc0451c133bc0040a68b1c31
