### ISSUE TITLE
Host install binaries in GitHub Releases

### ISSUE THREAD

**Issue by DenisCarriere** [GetScatter/ScatterDesktop#11]
The windows/ubuntu/macos install files should not be stored in the git repository, when creating official releases, add the binaries to the GitHub release section.

Can you remove https://github.com/GetScatter/ScatterDesktop/tree/master/release

It takes FOREVER to download the Git repo.

**Comment by nsjames** [comment]
Oh. Yeah.
Cloning on a new computer for the first time and this is NOT fun.

**Comment by DenisCarriere** [comment]
🤣 Not fun indeed!

Once the releases are removed from the Git repo, you can easily clean them out using BFG Repo Cleaner

https://rtyley.github.io/bfg-repo-cleaner/

**Comment by DenisCarriere** [comment]
🎉
