### ISSUE TITLE
RE: Update and Recover on new PC

### ISSUE THREAD

**Issue by jiangh77** [GetScatter/ScatterDesktop#110]
When a newer version of Scatter Desktop Wallet come out do I need to un-install the older version before installing the newer version or can I install the newer version on top of the older version without un-installing the older version
When I get a new PC and try to recover Scatter Desktop Wallet on new PC do I only need the private active key of EOS in order to recover the Scatter Wallet

**Comment by nsjames** [comment]
You can just install the newer version on top.

And yes, you can either rebuild from private keys, or from the exported backup.

**Comment by jiangh77** [comment]
Thank you very much
Have a great week
