### ISSUE TITLE
cannot create 2 servers with one network id

### ISSUE THREAD

**Issue by sss-CRS-sss** [GetScatter/ScatterDesktop#118]
cannot create 2 servers with one network id.
If one node has problems, then why should the user suffer without being able to use the other? Adding two nodes with one network id is not possible.

**Comment by nsjames** [comment]
Generally the node you would add would be a load balancer ( like the Scatter endorsed nodes ). 
You **can not** have 2 networks with the same `chainId` as that is their unique identifier.
