### ISSUE TITLE
Mac App Launched w/ Dev Console Open

### ISSUE THREAD

**Issue by gnollio** [GetScatter/ScatterDesktop#12]
Upon launching Scatter Desktop for Mac, the app displays with the developer console open. It also indicates two font files are not found.

<img width="1392" alt="screen shot 2018-07-27 at 7 35 22 pm" src="https://user-images.githubusercontent.com/37458577/43351229-a1a96176-91d4-11e8-8ce6-e81735fb6c9b.png">

**Comment by lil2good** [comment]
Same happens on my Mac.

**Comment by nsjames** [comment]
This is fixed now, and there is a new button top-left to open the dev console if needed.
