### ISSUE TITLE
mainnet account not shown in the tokens accounts list

### ISSUE THREAD

**Issue by jjssoftware** [GetScatter/ScatterDesktop#125]
As mentioned in telegram I have a couple of mainnet keys/accounts added to scatter desktop but only one of those accounts is shown in the tokens accounts view. 

On a hunch I deleted my jungle and kylin networks from scatter, refreshed the tokens and the account that was missing then appeared.

I have a feeling that this issue could be somehow related to my account name being present both in the mainnet and also in the testnets and scatter is getting confused where the account is.

**Comment by nsjames** [comment]
This should fix this issue 2f689aa303ac0d3ef8473970c8dff28935c33b6d
