### ISSUE TITLE
Transfer Request "Amount" / warning user if they're sending 0 EOS

### ISSUE THREAD

**Issue by NorseGaud** [GetScatter/ScatterDesktop#126]
Mac OSX

<pre><\a href="scatter://transfer/?payload=meostricsnet/0/donation_from_graphs_site">
    <\button>Donate with Scatter<\/button></pre>

This opens the `Transfer Request` box in my app.
I can then click on an account to use, and it will take me to:
<img width="235" alt="screen shot 2018-10-14 at 12 15 30 am" src="https://user-images.githubusercontent.com/5896030/46912557-4c537b80-cf46-11e8-9546-4d7f7e739a28.png">

1. I'd like to be warned about not populating the `Amount` field before I can click through. Maybe a highlight too. It wasn't crystal clear on first impression.

2. Also, when I add 1 to the field but then remove it, I see NaN EOS to ... instead of 0

<img width="235" alt="screen shot 2018-10-14 at 12 17 43 am" src="https://user-images.githubusercontent.com/5896030/46912562-976d8e80-cf46-11e8-9eb6-40ed2c46886e.png">

**Comment by nsjames** [comment]
Thanks for the report, fixed for next release

![image](https://user-images.githubusercontent.com/10360675/47262038-c73c0980-d4e5-11e8-8ab5-8fc87efa8593.png)

1d1c7bcd7b65719137ed2bd037142c1de6fcd8e6
