### ISSUE TITLE
yarn install throws "ERROR: [Errno 2] No such file or directory: 'install'"

### ISSUE THREAD

**Issue by mschoenebeck** [GetScatter/ScatterDesktop#129]
Fresh clone and got this error...

**Comment by nsjames** [comment]
Maybe this?

https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install

**Comment by nsjames** [comment]
Closing as I'm pretty sure this isn't a Scatter Desktop error.
