### ISSUE TITLE
[Mac] Can't use CMD+V to paste

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#13]
Initially I only noticed that in my mac release (8.0.0) I wasn't able to press CMD + A to select all text. But another user reported that they weren't able to press CMD + V to paste the password or private key and I realized that this didn't work for me neither.

Interestingly enough I can only replicate this problem in the release version after running `npm run release-mac`.

When running the local development version with `npm start && electron .` it works fine as expected actually.

![image](https://user-images.githubusercontent.com/2923/43351461-51a3c3a4-91e0-11e8-83fd-77372dc628d5.png)

**Comment by frankwei98** [comment]
I have the same problem on my mac too. 
I am running the latest version of Scatter Desktop and I can't paste anything to Scatter desktop app

**Comment by Soleone** [comment]
Got another report of this today. Kind of a showstopper for people like me who use a 32 character scatter password with a password manager.

**Comment by nsjames** [comment]
Fixed and will be pushed with next release: 93f9fe1b4b738e0098c6d38e61e9ecdc66dd9ece
