### ISSUE TITLE
Scatter tutorial showing again after upgrading to new version

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#132]
I set up Scatter Desktop on my Mac before, last time I reset at 9.0.0 probably. Not 100% sure which version I was running last exactly it could have been 9.0.0 or a later version.

When I started Scatter it notified me of a new version. After downloading and starting that, after I entered my Scatter password I saw the tutorial of the vault again.

I clicked the vault and then it asked me to click the New button in there even though there was already an entry in the vault.

Not a big deal, but could confuse some users.

**Comment by nsjames** [comment]
There was definitely a bug in one of the versions which caused that, not sure if it still exists in the latest one as I remember fixing it ( or something like it ). I'll do a fresh install of Scatter soon and check if it's still there in the latest version.
