### ISSUE TITLE
https firefox, SecurityError: The operation is insecure.

### ISSUE THREAD

**Issue by lljxx1** [GetScatter/ScatterDesktop#133]
looks like https has SecurityError

**Comment by nsjames** [comment]
The application you are using hasn't upgraded to the latest `scatter-js` which fixes issues for Firefox ( and all other browsers. )

**Comment by lljxx1** [comment]
i'm using scatter-js@2.5.2, this is latest version?

**Comment by lljxx1** [comment]
https://www.npmjs.com/package/scatter-js, you should update npm

**Comment by nsjames** [comment]
That's the old scatter-js, you should move to `scatterjs-core` with `scatterjs-plugin-eosjs` now as it has lots of upgrades.
