### ISSUE TITLE
Airgap option?

### ISSUE THREAD

**Issue by Another-Joe** [GetScatter/ScatterDesktop#135]
This may be an enhancement request. Is there an option to grant permissions from an airgapped account? If not, are there plans to do so? If not, can there be? ;)

**Comment by Another-Joe** [comment]
Thanks,
I think the latter.
Some sort of protocol for users to maintain airgapped accounts and still be able to use Scatter. For example, we had used Greymass' ability to approve transactions from an airgapped machine to vote. But we cannot claim airgrabs without signing in to EOSToolKit, meaning we need Scatter. The idea would be to be able to approve the transaction from the airgapped machine so it can be "activated" (signed?) on a non-airgapped one.
Sorry for the terminology blunders. Still figuring this stuff out.
Thanks. again.

**Comment by nsjames** [comment]
Well really, you can sign those contracts through the eos-voter contract tool.
It's not really the intention of Scatter to support that kind of behavior at the moment since it's primarily meant to be a hot wallet. Once the EOSIO ledger app supports dapps then that will become a safe way to do things like that from Scatter.

**Comment by Another-Joe** [comment]
Since I hadn't seen any support for eos-voter on EOSToolKit, it didn't occur to me that it was possible without Scatter, unless one had some programming ability. Even looking at it now, my guess is that the average Joe isn't going to figure it out. And I'm not average. ;) 
Thanks for the response. I know this isn't the place to get eos-voter support. Thanks for your work, nsjames. It's a great tool.
