### ISSUE TITLE
Loss of saved keys

### ISSUE THREAD

**Issue by nsjames** [GetScatter/ScatterDesktop#151]
A user seems to have lost keys when upgrading versions from 9.2 to 9.5.
This occurred after a warning from the installer that Scatter was already open.

**Comment by Soleone** [comment]
Tried to replicate but wasn't able to using the following steps on Windows:

### Cleanup 

1. Deleted folder `C:\Users\<YOUR_USERNAME>\AppData\Roaming\scatter`
2. Uninstalled Scatter from `C:\Users\<YOUR_USERNAME>\AppData\Local\Programs\scatter` via `Uninstall Scatter.exe`

### Install 9.2.0

3. Downloaded and installed [Scatter 9.2.0](https://github.com/GetScatter/ScatterDesktop/releases/download/9.2.0/win-scatter-9.2.0.exe)
4. Set up new password
5. Imported 2 different private keys and even generated 2 new key pairs
6. Tested and connected Scatter once on e.g. [myeoskit](https://www.myeoskit.com/tools/bandwidth/stake), myeoskit permission was saved under Apps
7. Restarted Scatter, everything is still fine

### Install 9.5.0
8. Downloaded and installed [Scatter 9.5.0](https://github.com/GetScatter/ScatterDesktop/releases/download/9.2.0/win-scatter-9.2.0.exe) while old Scatter is still open - install dialog notes folder exists and will be updated, then installer complains scatter is still open, pressing okay closes it and continues with no problems
9. Asked for current scatter password, works as expected
10. In the vault all 4 key pairs are still saved correctly

The only thing that seemed to have gotten lost was the myeoskit permission, it was no longer showing up under Apps. But that might be expected, not sure.

**Comment by nsjames** [comment]
It seems like he might have been on the version that allowed multiple Scatter instances to be opened at the same time and would conflict when trying to save to disk ( one would try to save, the other would pick it up and save over it because of changes, going back and forth between them ).

998acf725095815677c09cd663f1315ef5583cb1 this ticket should solve any other issues created by upgrading as the filenames now include the version and a new backup file will be issued when a new version is detected, leaving the user with a backup of their last version.
