### ISSUE TITLE
Changing the recipient when sending resets the token to EOS

### ISSUE THREAD

**Issue by grahamPegNetwork** [GetScatter/ScatterDesktop#152]
Per Zane in Scatter main group:
Any time you go to send a token and then update the RECIPIENT name the currency token being sent will CHANGE AUTOMATICALLY back to EOS from whichever token you had selected.

**Comment by grahamPegNetwork** [comment]
Tested on 9.4.0. I entered a recipient, selected a custom token, then changed one character in the recipient and saw that the selected token reverted back to EOS. The quantity does not reset leading to potentially dangerous situations if the user is not vigilant.

**Comment by Soleone** [comment]
Seems like the error is happening here: https://github.com/GetScatter/ScatterDesktop/blob/7b276db98468d5290be45581bc5e9871932d0873/src/views/Transfer.vue#L307

**Comment by nsjames** [comment]
e3eaad3faee880cc720dfaf75d61e714776ebfdf
