### ISSUE TITLE
Feature/UX: Prompt users to save their private keys elsewhere by default

### ISSUE THREAD

**Issue by grahamPegNetwork** [GetScatter/ScatterDesktop#153]
While initially prompted by the #151 incident, this is something that should probably be addressed in general. When a user generates keys, in addition to saving to their vault, the user should be prompted to back up the keys somehow. Other wallet software requests that the user copy the key (and verify it in some cases) before they can proceed. In the case of Scatter, upon naming and generating a key the process appears "done" when showing public keys.

One thing to also consider is that when setting up Scatter for the first time, users are given a mnemonic. Users may have preconceptions about this, thinking it is like an Ethereum mnemonic allowing for HD wallet creation and thinking that their mnemonic would allow them to generate private keys in the future. In reality this is a dangerous misconception, and if users rely solely on scatter's backups, any number of failures can cause them to lose their private keys.

(hardware failure, backup corruption, glitches, user error, ransomeware etc)

**Comment by Soleone** [comment]
One comment regarding the mnemonic: I noticed it has always been a bit of a point of confusion. Normally one is used to a mnemonic being used as a seed to generate new keys with.

I think maybe just because we _can_ have an alternative version of the password in case we lose it doesn't mean we should do it, it doesn't quote seem worth the extra complexity. Unless of course I'm missing some context here are more future plans with these seed words.

**Comment by grahamPegNetwork** [comment]
I would agree with that. I'll admit I don't quite understand the purpose, so perhaps there are things I need to know about it. From what I understand it's basically a backup for your password in case you forget it? Given the sensitivity, it seems like that would be more complicated to save offline than a password. 

Personally, I would (do) treat the Scatter DB/backups as a convenience. I don't foresee ever using the mnemonic to recover my account, if I ever had to I would lean toward a fresh start and importing my private keys again.

If it were a democracy, I would vote for the removal of the mnemonic. Access level, password. If you forget your password, restore your private keys. Always back up private keys, without exception, a "mandatory" process when generating new keys. If users want to ignore warnings and not back them up, only then should they be able to lose access to crypto assets.
(IMHO)

**Comment by nsjames** [comment]
6620f963e19d237485260168912d79f400ccbe8a this automatically forwards to the export key panel after creating a new keypair from inside Scatter.

**Comment by nsjames** [comment]
> I would agree with that. I'll admit I don't quite understand the purpose

It's the **only** way to regain access to your Scatter if you've lost your password. With the centralized backup service coming out soon that becomes even more important as you can not simply "change your password" like you can in a normal service. If you lose both, your keychain is gone forever.


> Given the sensitivity, it seems like that would be more complicated to save offline than a password.

Most passwords people use are generated from password savers like lastpass which end up being some 32 char randomized password. The backup phrase it significantly easier to write down ( and possibly even remember ).

> I don't foresee ever using the mnemonic to recover my account 

It's actually been used quite frequently by users. Let's not forget that we are developers and know a thing or two about all this. The general user doesn't really understand the impact of not backing up their keys, and even if they do they are normally stored on the same single machine. Possibly encrypted in lastpass with the same password, which they can lose.
