### ISSUE TITLE
Problem importing many accounts at once

### ISSUE THREAD

**Issue by nsjames** [GetScatter/ScatterDesktop#155]
It looks like when trying to import accounts from a key with a large number of linked accounts Scatter just doesn't import them. 

The entire request should be segregated into multiple requests and incrementally add the accounts to Scatter to avoid timeouts and race conditions.

**Comment by allthingsgo** [comment]
I don't know how to import a second EOS account after the first 'reg' session failed somehow.. I run Desktop Scatter of Mac OS.  anyone else reported such issue? Or it is simply to go into dirs and deleted previous keys?

**Comment by nsjames** [comment]
b69ea24d838aceb6bea491a5a2f830e3b893dcc6 for now, I'm just elongating the timeout until an API service is online to pull all accounts with a single API call.
