### ISSUE TITLE
User rejected the signature request with ledger nano S

### ISSUE THREAD

**Issue by cubotar** [GetScatter/ScatterDesktop#158]
I'm trying to execute a manual refund action through bloks.io with my ledger nano S and keep getting this error message : 
{ "type": "signature_rejected", "message": "**User rejected the signature request**", "code": 402, "isError": true }
Nothing is showing in the screen ( no confirm transaction )
same error with eostoolkit. Am I missing something ?
Thanks for the help

**Comment by nsjames** [comment]
Refund isn't yet supported on the EOS Ledger App. We're all waiting for the next update of that app so that it will work in all wallets.
