### ISSUE TITLE
Balance did not update after sending tokens

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#166]
I just sent a transaction from within Scatter using the Send button which went through fine. But afterwards on the Home screen the token balance was not updated and still showed the old amount. Had to manually press the refresh button to see the new EOS balance.

Might make sense to issue an automatic token balance refresh after the Send feature is used. I guess it should optimally wait a second or two to give the transaction some time to get processed.

Or alternatively maybe the refresh button could just be highlighted to remind the user to manually refresh themselves.

**Comment by nsjames** [comment]
8f4376e68653434699bd10819a8066ed9c7aa0e1 fixed here

**Comment by nsjames** [comment]
We'll have to think about the timeout though, since not all blockchains have the time lag. 
Might need to add a pending transactions list in the new UI.
