### ISSUE TITLE
Does not support https://eoslaomao.com/bankofstaked

### ISSUE THREAD

**Issue by helperShang** [GetScatter/ScatterDesktop#167]
Does not support https://eoslaomao.com/bankofstaked

**Comment by nsjames** [comment]
This is an issue on their side and not ours. You'll have to contact them to have them fix their scatter-js integration. 

![image](https://user-images.githubusercontent.com/10360675/47910712-5c52e100-de9c-11e8-9780-e655051fd89d.png)

**Comment by helperShang** [comment]
thanks
