### ISSUE TITLE
getArbitrarySignature does not work on macOS

### ISSUE THREAD

**Issue by vtornik23** [GetScatter/ScatterDesktop#175]
I'm trying to authenticate users in my game to login to my game-server.
I need some robust way to determine them. So i tried to use getArbitrarySignature and it works, but:
on the macOS, the scatter-standalone app immediately returns:
"{type: "signature_rejected", message: "User rejected the signature request", code: 402, isError: true}"

without any notification window, as it should be.
Is it a bug? Or maybe i should use some other function, to sign some arbitrary "secret-string"?

**Comment by nsjames** [comment]
So wait, the arbitrary signature works on windows, but not on macOS?

**Comment by vtornik23** [comment]
```
async function ScatterSign(value) {

    let publicKey ="EOS7MPNpyvHwSurCByVGS6hTyojgR1TXUAKpi2taicMMadttgvPXU";  //hardcoded for now
    let data = '12charstring';                // Anything, or a hash ( sha256 )
    let what = 'reasonDescription';     // The reason you are requesting a signature from a user.
    let isHash = false;               // Only set to true if the `data` is a hash

    ScatterJS.scatter.getArbitrarySignature(publicKey, data, what, isHash).then(signature => {
        console.log("Signature: "+ signature)
    }).catch(error => {
        console.log(error)
    });
}
```
Scatter Standalone 9.6

Works fine on Windows10
Don't works on MacOS
Don't works on Win7

**Comment by nsjames** [comment]
Are you sure that Scatter has that public key inside of it?
There's two cases where that error is thrown, one if the user rejects the signature popup, and the other when that key does not exist anywhere within the user's Scatter.

**Comment by nsjames** [comment]
Relevant code: https://github.com/GetScatter/ScatterDesktop/blob/master/src/services/ApiService.js#L448

**Comment by vtornik23** [comment]
Hi @nsjames 
My fault! 0_o
Now it works like a charm! Thank you very much, and sorry for that :)

Yuri
