### ISSUE TITLE
Download link for new version update does not work

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#176]
> New Update!
> There is a new Scatter update available. Do you want to download it?

When I press **Yes** nothing happens. This is Scatter 9.5.0 on Windows 10.

**Comment by A-damW** [comment]
Same here,
Lubuntu 17.10-x86_64
Default browser: Google Chrome 64.0.3282.140
linux-scatter-9.5.0-x86_64

**Comment by nsjames** [comment]
If you guys transfer some tokens to another account, does the link to the transaction hash after transferring open your browser?

**Comment by A-damW** [comment]
Yes,
when using the 'Send' function from within Scatter, clicking the transaction hash link opens my browser.
Works for both eosflare.io and bloks.io selected in Scatter block explorer settings.
Tested on: 9.5.0, and 9.6.0

**Comment by nsjames** [comment]
Looks like it might just be an error with the update link then. Thanks for the info, I'll run some tests on it

**Comment by Soleone** [comment]
Seems like it is still not working on 9.6.0. Got some people worried in the channel that this popup didnt do anything in light of the recent vulnerability patch, so might be worth prioritizing this here.

**Comment by A-damW** [comment]
Confirmed not working on 9.6.0 linux.
However, the Settings -> "Update Available" button does work.

**Comment by nsjames** [comment]
This __should be__ fixed in Scatter 10 as it no longer uses the URL returned from github, but a hardcoded one that forwards to the `/releases`
