### ISSUE TITLE
Duplicate TRON network in settings

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#177]
Noticed in the **Networks** settings that I had two entries for **Tron Mainnet**.

I was on 9.6.0, but this is on a Windows machine that upgraded from a few previous Desktop versions.

Looking at some of the code I currently suspect that [this piece of the migration logic](https://github.com/GetScatter/ScatterDesktop/blob/84e8776f41a03d7ae322b710550a5721935b50e3/src/migrations/versions/9.5.0.js#L9) didnt quite achieve the deleting of the previous Tron entry for some reason, maybe?

![tempsnip](https://user-images.githubusercontent.com/2923/48035500-42323080-e132-11e8-8ef4-9fb24d389b75.png)

**Comment by nsjames** [comment]
Fixed for next release
