### ISSUE TITLE
Safari and e.g. betdice no longer detecting Scatter

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#178]
When visiting e.g. betdice.one on **Mac** using **latest Scatter Desktop** and **Safari** instead of a login popup the website doesnt seem to detect Scatter. Clicking the login button on the website brings up this:

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/2923/48051756-f7d1a380-e173-11e8-900f-53c8bb7caf91.png">

Note the error at in the console regarding the **insecure websocket**:

[blocked] The page at https://betdice.one/ was not allowed to run insecure content from ws://127.0.0.1:50005/socket.io/?EIO=3&transport=websocket

### Notes

* Using **Chrome** or **Brave** worked fine
* Using **eostoolkit.io** worked fine in Safari

Joe 🐐, [Nov 6, 2018 at 3:24:54 AM]:
> aha I though this one was resolved a while back
> looks like a bug in the scatter wss / cert stuff

**Comment by nsjames** [comment]
I too cannot get to betdice one on Firefox and I don't see that they are using`wss` on chrome either.

![image](https://user-images.githubusercontent.com/10360675/48061062-6c353280-e1c6-11e8-85b0-afcc501a3fd8.png)

Looks like they just need to update their `scatterjs-core` lib to allow for Safari, Firefox, Edge, etc.
