### ISSUE TITLE
TELOS support

### ISSUE THREAD

**Issue by bitcoiners** [GetScatter/ScatterDesktop#18]
Please add support for TELOS blockchain. Currently, TELOS Testnet is not supported. 
http://testnet.telosfoundation.io
When adding keys only EOS and Ethereum are available choices. 
![image](https://user-images.githubusercontent.com/38520/43873796-6441586a-9bb2-11e8-8aa3-46b67a764fa7.png)

**Comment by nsjames** [comment]
No fork that changes signing/keystructure will be available.

**Comment by nsjames** [comment]
This goes deeper than Scatter. If the key structure changed them it affects eosjs as well. 
This might require another `plugin` designated specifically for TELOS. Blockchain plugins are very sparingly added to Scatter, as their existence multiplies development time. 

I'll accept a PR if it looks good and has wide support from a large number of users (10k+), but your team will need to maintain it consistently. 

Alternatively, you can just use EOS prefixes, and have instant support for both Scatter and eosjs.

**Comment by infinidi** [comment]
Support has been added here: #19, thanks @marlonwilliams, @nsjames!
