### ISSUE TITLE
TRON private key same as ETH?

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#182]
A user (and me) was confused that in the **Vault** when trying to **export your ETH or TRON private keys** that they're the same there. Only the EOS private key is different.

Is this a bug? Or expected, i.e. is TRON using the same private key scheme as ETH but a different public key representation?

### Replication steps:

1. **Import EOS private ke**y and observe that also ETH and TRON addresses were generated, both with different public keys
2. Click to **export private keys**
3. And **enter Scatter password**
4. **Select EOSIO format** and notice the original private key shows correctly
5. **Select ETH format** and note down private key
6. **Select TRON format** and note how that **private key is the same as the ETH private key**

**Comment by nsjames** [comment]
Yup, this is expected. Since a lot of tron's key structure is built on top of ethereum their private keys are the same. This was part of the big move recently to make any key put in create all public keys on top of them as there was no way to discern tron from ethereum.
