### ISSUE TITLE
Request of adding new explorer

### ISSUE THREAD

**Issue by linkdesu** [GetScatter/ScatterDesktop#189]
I hope [EOSPark](https://eospark.com/) can be selected by as one of block explorers for checking transactions after trading. I noticed that you had connected with EOSflare and Bloks. But we are proudly introduce ourselves [EOSPark](https://eospark.com/) is a powerful popular block explorer in the field. And compared with EOSFlare and Bloks, we are having more functions and providing more services. Thanks a lot.

Available URL templates:
- contract: https://eospark.com/{net_type}/contract/{contract}
- account: https://eospark.com/{net_type}/account/{account}
- address: https://eospark.com/{net_type}/address/{address}
- block: https://eospark.com/{net_type}/block/{block_id}
- transaction: https://eospark.com/{net_type}/tx/{transaction_id}

Available net_type value: 
- MainNet
- Jungle
- Kylin

**Comment by nsjames** [comment]
A new repository for explorers has been added here: https://github.com/GetScatter/ScatterExplorers

And eospark has also been added to that list. It will be enable-able in the next release of Scatter.
You can see it on the api here: https://api.get-scatter.com/v1/explorers
