### ISSUE TITLE
gravatar on bloks.io not working with ledger nano s

### ISSUE THREAD

**Issue by GreenAces** [GetScatter/ScatterDesktop#193]
When using the ScatterDesktop (latest version) on Linux, I was trying to create a gravatar using my ledger hardware wallet on the blok.io but I was greeted with the following error message:

**Side Note:**
To access the gravatar go to account > profile 

**Error Message:**
Error
{ "type": "signature_rejected", "message": "User rejected the signature request", "code": 402, "isError": true }

**NOTE:**
I did not reject the request. I sign in using the owner and the child account and still produced the same error.

**Comment by nsjames** [comment]
Ledger did not allow dapps until a day or two ago, and we have yet to have a chance to run tests on the current implementation to see whether it needs changes or not. There is already an open ticket for this.
