### ISSUE TITLE
Issue with sending transactions with Scatter Desktop on Linux Mint

### ISSUE THREAD

**Issue by shakhruz** [GetScatter/ScatterDesktop#194]
I'm using Linux Mint 18 and I can't make any transactions with Scatter desktop.

not sure how to debug this one, but I discovered that after I removed chrome extension I was not able to complete a transaction with Scatter anymore. I tried betdice, eosbet, some wallets, all to the same result - I could log in and confirm that I want to make a transaction, but nothing happens after that.

When I was working with ScatterJS library I was also able to launch scatter desktop from my Js code, confirm a transaction, but never got control back. Promise was still pending (forever). no errors, no messages.

**Comment by shakhruz** [comment]
![image](https://user-images.githubusercontent.com/6615/48311964-7e99dc80-e5c9-11e8-8787-859c05678548.png)

maybe this will help. It also hangs the whole system sometimes when I try to start it

**Comment by shakhruz** [comment]
reinstalling and reimporting my private key solved the issue. I think the problem was that I created account with 9.5.0 and then install 9.6.0 on top of it

**Comment by nsjames** [comment]
Yeah that looks like the data got corrupted mid-use. There's a fix for the next release which should handle this and prevent that from happening ( verifies saved data before overwriting stored files. )
