### ISSUE TITLE
Scatter doesn't retrieve the abi from nested actions

### ISSUE THREAD

**Issue by piecesnbits** [GetScatter/ScatterDesktop#195]
When doing msigs on eosio.msig we need to update the eosjs abiCache so that the actions inside the msig transaction can be serialized. However scatter doesn't sync it's persistent cache with eos.fc.abiCache nor it isn't able to retrieve the abis from these nested actions. 

bug reproduction:
1) call eosio.msig "propose" action with a trx that contains a non system contract action (you get an eosjs error because the abi from the nested action is not cached)
2) add the abi from the above action/contract to eosjs abiCache `eos.fc.abiCache.abi(code, abi)`
-> eosjs doesn't error any more because we've added the missing abi to cache. However scatter still doesn't know about this new abi.
![image](https://user-images.githubusercontent.com/44613132/48317657-94bd9200-e5f5-11e8-9945-f8fc828f9862.png)

**Comment by piecesnbits** [comment]
possible solutions: 
1) watch/compare for eosjs cache updates and mutate scatters cache accordingly (by getting the abi from chain)
2) only do the above when scatter doesn't find an abi in it's cache.

**Comment by chendatony31** [comment]
Same error when using the eosjs16, but it is ok now with eosjs20. 
Still, I hope it could be fixed though.  :)

**Comment by nsjames** [comment]
Should be fixed with eosjs2 support
