### ISSUE TITLE
Unable to create an EOS account

### ISSUE THREAD

**Issue by Nuc1eoN** [GetScatter/ScatterDesktop#199]
When I create a new vault Scatter does not show me any EOS account. There is only Tron and Etherium.
Under "Show Public Keys" it shows EOS though.
This might be related to #198 however I am not always getting the error mentioned there when creating a new vault.
1)
![scatter2](https://user-images.githubusercontent.com/2538022/48452248-8666a600-e7ae-11e8-9499-b45071ec8454.PNG)
2)
![scatter3](https://user-images.githubusercontent.com/2538022/48452250-88306980-e7ae-11e8-84f9-e819b0d6ccf4.PNG)

**Comment by nsjames** [comment]
Scatter does not create EOS accounts for you, as they need to be paid for. Please visit https://eos-account-creator.com and follow the directions there. Once you have an EOS account you can import it into Scatter.
