### ISSUE TITLE
[Mac] Background color is grey instead of white

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#2]
![image](https://user-images.githubusercontent.com/2923/42549372-cb69462c-8499-11e8-8cdb-337858fd7a38.png)

Also probably causing the Delete button in the Keypairs section to not be visible by default:

![image](http://g.recordit.co/4WpTEbJC0l.gif)

Build log after cloning from github: https://gist.github.com/Soleone/62029cadf63161bad79be26f5e2d1555

**Comment by nsjames** [comment]
I **might** have pushed a fix for this but not sure yet. We'll need to check on a mac machine.

**Comment by Soleone** [comment]
Let me try and report back...

**Comment by Soleone** [comment]
Yep, looks fixed:

![image](https://user-images.githubusercontent.com/2923/42645521-41de79b6-85cc-11e8-8588-f287399b230c.png)

![image](https://user-images.githubusercontent.com/2923/42645502-3272538a-85cc-11e8-87c8-98cf388e590f.png)

🎉
