### ISSUE TITLE
Application links being deleted when hiding EOS blockchain

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#201]
A user noticed that when using the hide blockchain feature in the vault that all application links on the Home screen get deleted and dont come back when the EOS blockchain gets re-enabled. I was able to replicate this.

### Replication Steps

1. Ensure you have some application links already stored in Scatter
2. Click **Vault**
3. Click your EOS account key
4. Click **Show Blockchains**
5. **Remove all checkmarks** from all blockchains there
6. Click **Refresh Linked Accounts** in the top right (but I think can also just close this window without this step)
7. Note how on the Home screen all Application Links are gone. I am not 100% sure but I had a feeling it also removed application links from one of my other EOS accounts that I didnt set to hide under its Show Blockchains setting. In any way so far, it might still be mostly expected
8. Repeat steps 2 - 4 and then **re-add all checkmarks** for all blockchains there
9. Click **Refresh Linked Accounts** in the top right - it took a long time to complete for me, 20 seconds or so.
10. Back on the Home screen **all the previously stored Application Links are still gone**

### Recommendation

I would have expected the application links to come back as long as I'm not completely deleting that key and its associated account.

Alternatively I would have expected at least some warning prompt that all application links will be deleted.

Scatter Desktop 9.6.0, Windows 10

**Comment by nsjames** [comment]
The next release shows warning for this, but the accounts and permissions will still be deleted as it's not just hiding them, it's removing them from Scatter which makes it have to do less processing ( less fetching from chain for various things like tokens and resources )
