### ISSUE TITLE
Apps link in home apps list do not open app in browser

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#203]
Relevant for v10

When clicking the title, it doesn't open in browser. 

You are using a method to open the link and I'm not sure why:

`openApp(origin){
				const data = this.getAppData(origin);
				if(data.url.length){
					this.openInBrowser(data.url);
				}
			},`

![screen shot 2018-11-16 at 10 22 49 am](https://user-images.githubusercontent.com/814302/48607357-cdf55980-e989-11e8-9b6e-0b47e3575a00.png)

**Comment by ramijames** [comment]
After poking around more it looks like data.url.length is always zero, so no links are passed

**Comment by nsjames** [comment]
This app has no meta data in our scatterapps repository so it doesn't have a url and can't be opened by clicking on it. We can't use the applink as a url without vetting them first as it poses a risk to the users.

**Comment by ramijames** [comment]
So I’ll go through all the apps and vets them myself.

**Comment by nsjames** [comment]
The ones inside the scatterapps list should all be pre-vetted from when they were merged or they shouldn't have been merged.
