### ISSUE TITLE
Getting asked twice for password when exporting Private Key to QR Code

### ISSUE THREAD

**Issue by Nuc1eoN** [GetScatter/ScatterDesktop#205]
After pressing "Export Private Key" you get asked for your password. However after that, the next step is to choose `Key` or `QR Code`. After pressing `QR Code` you get promted for a PIN. If the PIN is different from the password you need to type in the password again. This could be avoided by simply asking for the password only after selecting `Key` or `QR Code`.

**Comment by nsjames** [comment]
Fixed for next release (10.0.0) on `ui_revamp` branch
