### ISSUE TITLE
Unable to send transaction v9.6.0 "gcm: tag doesn't match"

### ISSUE THREAD

**Issue by codysaylor** [GetScatter/ScatterDesktop#206]
Trying to send a transaction (eosio.token) from Scatter Desktop as well as bloks.io (authenticated via Scatter Desktop) throws this console error:

asyncToGenerator.js:20
Uncaught (in promise) 
corrupt messsage: "gcm: tag doesn't match"

I do still have the Chrome extension installed - could this be part of the problem?

Windows 10
v9.6.0

**Comment by Soleone** [comment]
Definitely recommended to uninstall or at least disable the chrome extension in chrome extensions settings. But this error sounds like potential data corruption [I heard of today](https://t.me/Scatter/64435).

Apparently [fixed in 9.6.1](https://t.me/Scatter/64447).

**Comment by codysaylor** [comment]
Thanks for that point of reference - if anyone else is getting this error, here's how I resolved it:

1. Create a backup of your Scatter
2. Remove the items in your vault
3. Import your account again
