### ISSUE TITLE
Error trying to export private key

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#208]
I ran into this error before once, I was just about to submit an issue then I thought it might have been too much of an edge case to matter. But then today someone else saw a similar error message, but not with the same replication steps as me.

![image](https://user-images.githubusercontent.com/2923/48922938-2b9d1080-ee78-11e8-8515-0281c7370922.png)

My original replication steps were as follows, but this is not what happened to this person here:

1. Import new private key from hardware wallet
2. Right on the next screen it will actually allow clicking the export private keys button even though that is normally not available for hardware wallet based keys
3. This resulted for me in the same error message as above

But this person today are not using a hardware wallet, and apparently did not import a key  in the previous step it was already imported before. They just tried exporting one of their EOS private keys. After repeated attempts it eventually worked.

**Comment by nsjames** [comment]
closed now as the structure for these exports has completely changed
