### ISSUE TITLE
License

### ISSUE THREAD

**Issue by csajedi** [GetScatter/ScatterDesktop#209]
Hi, I want to hack on this cool new tool you've created but there is no license and the ambiguity surrounding unlicensed source code scares me away from even downloading and installing it. Can you decide on a license for the larger community? I suggest GPLv3 but it is not suitable in every case.

**Comment by nsjames** [comment]
Well hot damn. I have no idea how that slipped through for so long. 
I've updated the project to include a license, and also upgraded our standard MIT with a GPL license to also force all derivatives to be OSS too. Thanks for letting me know.
