### ISSUE TITLE
Hardware integration: Show dialog that action on hardware is required

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#21]
My first time using the hardware wallet when it was time to sign the transaction I didn't realize I had to look at the hardware wallet. The Scatter side seemed frozen and I wasn't sure what to do.

Would be nice to show some sort of loading animation and message similar to what Ledger does like "Look at your hardware wallet and confirm the transaction details there."

**Comment by nsjames** [comment]
You're absolutely right, I'll have to add a little popup there telling the user to look at their hardware.

The flow for this still isn't great yet tbh, as it might just outright fail if the hardware isn't connected with no ability to connect after the fact

**Comment by nsjames** [comment]
Forgot to close this, it's been fixed since 9.4
