### ISSUE TITLE
Status message during private key importing

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#212]
Regularly there are users having issues pasting their private keys into Scatter. For some reason it is not accepting their key and they don't really get any feedback on what might be wrong.

It would be nice if below the input field some status message could dynamically update when the input changes to catch potential user errors early.

1. Is the key not long enough yet?
2. Is the length okay but format still invalid?
3. Is there any error, e.g. connecting to a server or backup storage? 

![image](https://user-images.githubusercontent.com/2923/49056183-9a57d200-f1c8-11e8-9e26-f07b026c189d.png)

I had a user today who was sure he pasted the right private key but nothing was happening, it was not being accepted. In the javascript console he saw an error related to BackupService which reminded him that his backup location in Scatter was set to a drive that was unplugged. But even after plugging it in and restarting it didnt end up working, no more error in the console.

Would be nice to rule out as many things as possible especially (1) and (2).

**Comment by nsjames** [comment]
![image](https://user-images.githubusercontent.com/10360675/49109641-e885d780-f293-11e8-8f86-90a1f5fd3045.png)

For now i've added an error for at least when a key isn't the minimum length for
any blockchain (51). We'll have to do some more parsing in the future possibly 
due to multiple blockchains and checking against types.

**Comment by nsjames** [comment]
There's now a fake button there which when pressed will just show "Invalid Private key" as the error message.
