### ISSUE TITLE
Feature request: Bancor network integration

### ISSUE THREAD

**Issue by bitcoiners** [GetScatter/ScatterDesktop#215]
If would be nice to see value of tokens in Scatter (based on current price) and be able to exchange them from the wallet. This could be done by integrating with https://eos.bancor.network

**Comment by nsjames** [comment]
Exchange added for 10.1.0, will not include Bancor from the start but will be added gradually without need to update the desktop app.

**Comment by t3ran13** [comment]
app.bancor.networ - after login did not show actual balances
cant brodcast transactions, some error happens
