### ISSUE TITLE
Documentation: OS X minimum version?

### ISSUE THREAD

**Issue by bracklanna** [GetScatter/ScatterDesktop#217]
Please add somewhere on the website, or on the github page, what the minimum OS version requirements are for the current release of Scatter Desktop.

I.e. does it work with OS X 10.9 and later?  10.10 and later? 10.12 and later?  Requires Mavericks 10.13?

**Comment by nsjames** [comment]
It should be available across all modern versions of OSX, Windows and Linux. 
It looks like the minimum __might be__ macOS 10.10 (Yosemite)
