### ISSUE TITLE
Linux 9.6+ version don't start up

### ISSUE THREAD

**Issue by slayorktc** [GetScatter/ScatterDesktop#219]
Running Linux Mint 18.3.

9.6.0 x86_x64.appimage
9.6.1 x86_x64.appimage

Both of these version don't start the GUI or application. Nothing in the taskbar and nothing happens. Had to revert back to 9.5.0 which still works just fine.

Let me know what info you need or how to provide logs.

**Comment by jjssoftware** [comment]
This looks similar to the issue that I reported in the scatter elite test telegram group.

> I see occasional crashes with the v10 beta linux build on linux mint. This is not a new bug, I saw this occur in v9.6.1 too. When the crash occurs it hangs the OS requiring it to be buttoned. If I had to guess I'd say this is hardware / usb driver related because I've only seen this problem since hardware wallet support was introduced into scatter.

> The crash only ever occurs on initial scatter startup, once it's running it's fine. A scatter runtime log file would be really nice to track down what's going wrong here but in the absence of that I'll keep digging around to see if I can trap anything into an OS /var/log file

Nathan said he was going to introduce a crash log, I don't know if it got implemented, I asked and received no reply.

**Comment by jjssoftware** [comment]
Following the initial report I later added:

> I have a bit more info about this now. When the crash occurs it's not crashing the OS as I first thought, it's crashing cinnamon / the desktop manager. When linux mint looks dead following the crash, it's possible to revive it either by restarting Xorg with ctrl+alt+backspace or by dropping to a shell with ctrl+alt+f2 and then executing sudo service mdm restart

> When X crashes it looks like an immediate crash. There's nothing that I can find logged in the usual places at least i.e. journalctl, /var/log/kern.log, var/log/syslog, var/log/Xorg.0.log etc

> One thing I noticed is that when scatter crashes it leaves these files behind:

![photo_2018-12-30_13-04-52](https://user-images.githubusercontent.com/536164/50547552-8b36ca80-0c33-11e9-846c-5cf2d7b51d97.jpg)

> If I leave these files in place it would appear that I can't get scatter to start at all, all attempts result in the desktop crash. If I manually delete these files I'm sometimes then able to get scatter to start up successfully (if it doesn't crash for the reason that we're still hunting for).

This problem still exists today in v10.0.3

**Comment by slayorktc** [comment]
Too bad to hear it's still not fix. Luckily, I am still able to use
hardware wallet with 9.5.
