### ISSUE TITLE
Scatter 10 Hardware integration: Show dialog that action on hardware is required

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#222]
Seems like the fix for [this old issue](https://github.com/GetScatter/ScatterDesktop/issues/21) hasn't been ported to new Scatter 10 yet. 

![image](https://user-images.githubusercontent.com/2923/49838391-783d8280-fd78-11e8-860d-c27a28f4b367.png)

**Replication Steps:**

1. Issue transaction from e.g. eostoolkit.io using an EOS account tied to a Ledger Nano
2. Scatter dialog shows: "Sending... Scatter should appear shortly..."
3. Immediately the full Scatter dialog from my screenshot above shows with the transaction details -- nothing on  Ledger yet
4. After confirming the transaction details in Scatter by clicking **Allow** that dialog closes and you can now only see the dialog from (2)
5. A user might easily miss having to look at the Ledger now. When I do I immediately see the transaction details being scrolled through there on the hardware device

After that everything works perfectly, but I I would make sure when a hardware wallet backed account is detected that after (4) some new message from Scatter asks the user to look at their hardware wallet.

**Comment by nsjames** [comment]
native notifications now appear when hardware is required.

![image](https://user-images.githubusercontent.com/10360675/49932160-0c226200-fed1-11e8-96bc-8e2b6db4b0d3.png)
