### ISSUE TITLE
Scatter 10 transaction popup position

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#224]
Right now the transaction popup is positioned at exactly the bottom right corner, very tightly hugging it.

As a user my instinct is to slightly move it away from the right side to ensure I am not missing any piece of the window.

![image](https://user-images.githubusercontent.com/2923/50034907-25103d80-ffcd-11e8-9c6e-d406dfd226c0.png)

### Suggestion

Add at least 10 pixels of padding on both the right and bottom side to make it clear where the popup boundaries are:

![image](https://user-images.githubusercontent.com/2923/50035002-d1522400-ffcd-11e8-8a61-7975a3ef787c.png)

**Comment by nsjames** [comment]
Great idea. I didn't move it as much a 10 pixels but I moved it a few pixels away from the screen ( 10 looked a little funky being so far from the edges.
