### ISSUE TITLE
User reportedly lost private key after Scatter 10 upgrade

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#226]
Supposedly a key was removed from the vault after upgrading from Scatter Desktop 9.6.1:

> i just installed scatter 10 and one of my vaults has disappeared
> I had 3 and now i only have 2
> [upgraded] from the latest version
> i had 2 eos vaults
> and 1 worbli
> 1 of the eos vaults is gone
> i cant understand what happened
> Yes the only thing i did was download the new version,input the password and it was gone

Apparently apps entries were removed along with that:

> btw also all the apps that were linked to my scatter are gone along with that eos vault

https://t.me/Scatter/66943

**Comment by nsjames** [comment]
I forgot to mention it on the Scatter 10 release but all hardware keys had to be removed since their unique ID changed. 

I'm adding it to the release notes now <3
