### ISSUE TITLE
Scatter 10: Account list in login popup not scrollable

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#227]
> When i go to log into a dapp, say newdex or betdice, and scatter is asking me to select the account of mine to login with, that window does not alow me to scroll down through my different accounts, i have to put them in the search function to find them.
> Last scatter version i was able to just scroll down though all my accounts to pick witch one to log in with. not sure if I'm the only one having this problem or not?

https://t.me/Scatter/66929

**Comment by nsjames** [comment]
Fixed in patch: https://github.com/GetScatter/ScatterDesktop/releases/tag/10.0.1
