### ISSUE TITLE
Scatter 10: Chrome extension backup hangs during import

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#228]
Two independent reports:

### User 1:

> Ok so downloaded the desktop version 9.6 patch then installed 10 over it.
> Tried to import backup from chrome extension but it just sits there with spinning wheel. On a Windows machine. Any advice?

https://t.me/Scatter/66931

### User 2:

> can not restore chrome extension backup into scatter desktop.. is it expected behavior?
> yep the txt file generated from scatter chrome extension. scatter desktop 10 just hangs forever after i am trying to load it

https://t.me/Scatter/66989

**Comment by nsjames** [comment]
Fixed in patch: https://github.com/GetScatter/ScatterDesktop/releases/tag/10.0.1
