### ISSUE TITLE
[Feature] Add QTUM Support

### ISSUE THREAD

**Issue by asddsaz** [GetScatter/ScatterDesktop#230]
**Feature**: Add support and account management for [QTUM](https://qtum.org/) DApps.
___________________
Want to back this issue? Post a [bounty on it](https://www.bountysource.com/issues/67576218-feature-add-qtum-support)! We accept bounties via [Bountysource](http://www.bountysource.com/).

**Comment by Soleone** [comment]
Why QTUM over so many other blockchains out there?

**Comment by asddsaz** [comment]
@Soleone I haven't seen a single ETH alternative that is like QTUM. 
**Other chains:** Blockchains like ICON, Waves, AION, e.c.t appear to be more for enterprise and therefore have little need for every day users.
**QTUM**: QTUM is still doing strong for such a small community. Just look at there partnership with [Matchpool](https://www.matchpool.com/).

**Comment by nsjames** [comment]
You should have them reach out to us at business@get-scatter.com

We handle blockchain additions with the core teams of those blockchains personally so they need to make contact so we can start the process.
