### ISSUE TITLE
Don't know where to import my wallet with the previous generated 12-word seeds. 

### ISSUE THREAD

**Issue by wutalamanzheng** [GetScatter/ScatterDesktop#231]
Don't know where to import my wallet with the previous generated 12-word seeds.

**Comment by nsjames** [comment]
Scatter is not yet an HD wallet. The mnemonic you get is only a backup for your **password**.
If you want to restore a previous Scatter you need one of your automatic backup files.
The looks like this `scatter__44ef__10-8.json`
