### ISSUE TITLE
Unhandled rejection Error:

### ISSUE THREAD

**Issue by VtpVlan-oo7** [GetScatter/ScatterDesktop#24]
$ sudo npm i

Unhandled rejection Error: Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/ethereumjs/ethereumjs-abi.git /home/surya/.npm/_cacache/tmp/git-clone-e031a8d1
/home/surya/.npm/_cacache/tmp/git-clone-e031a8d1/.git: Permission denied

    at ChildProcess.exithandler (child_process.js:288:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:599:12)

can anybody tell us what we have to do ?

**Comment by nsjames** [comment]
You wouldn't happen to be in MacOS would you?

**Comment by VtpVlan-oo7** [comment]
nopes ! i have ubuntu 16.04

**Comment by nsjames** [comment]
This seems related to the same issue I have on Mac. Every time I pull the repo down I have to `rm -rf` the old folder and then npm I or else I get those missing dependencies. I think it might have to do with path permissions ( even though I've set them to different paths ) and npm not getting child packages which fail to mkdir silently.

**Comment by Soleone** [comment]
Just casually checking if this is likely still an issue worth tracking or closable?

**Comment by nsjames** [comment]
30 days with no reply let's close this up. If they return we can open it.
