### ISSUE TITLE
Scatter v10.0.3 cannot sign transaction using Ledger

### ISSUE THREAD

**Issue by sssamwong** [GetScatter/ScatterDesktop#241]
After updated to Scatter v10.0.3, transactions (Bancor and Chintai) can no longer signed using ledger as shown below. I'm using EOS app v1.2 in Ledger Live and arbitrary data was turned to yes. please help.
![screenshot 2018-12-25 at 1 43 50 pm](https://user-images.githubusercontent.com/30836199/50424317-bd93a100-089c-11e9-8ae0-4e43855cd016.png)

**Comment by nsjames** [comment]
This usually means a connection couldn't be made.
If you're using another ledger wallet ( like fairy ) at the same time it will cause issues.
Close all other ledger wallets and Scatter, unplug the ledger and then plug it back in and enter your PIN, open the EOS app on your ledger, and then open Scatter. 

If that works, please close the ticket. If not, let me know.

**Comment by sssamwong** [comment]
I tried but it still doesn't work..

**Comment by nsjames** [comment]
Have you also enabled the "Arbitrary Signature" in the settings for the EOS Ledger App?

**Comment by sssamwong** [comment]
Thanks Nathan. May I know if you are referring to "Arbitrary Data"? It's also turned to "Yes", but still not working..

**Comment by Soleone** [comment]
I think this will be hard issue to debug unfortunately. You seem to be the only person so far having this problem from what I've heard.

If you really thoroughly followed the suggestion in https://github.com/GetScatter/ScatterDesktop/issues/241#issuecomment-449929883 then I am not sure what else can be done in the meantime to address this. Some weird edge case on your machine that is blocking the Ledger.

Things to do to potentially help understand what's going on if you somehow can:

* try another computer
* try the same computer but not using ledger but using a normal imported private key, does that work?
* uninstall and re-install scatter

Grasping at straws here, but this does not look like an easily fixable issue right now. Any more info you can provide might help. E.g. which operating system are you on and which browsers did you try (maybe try alternative browsers).

**Comment by nsjames** [comment]
Cleaning tickets for Scatter 11 testing release (makes this ticket no longer relevant)
