### ISSUE TITLE
Recurring proxy vote happening too often

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#244]
I noticed that whenever I open my Scatter shortly after that I get a notification in my emails that my account did a proxy vote.

My understanding is that the automated proxy vote feature in Scatter should happen every 7 days. Instead it seems to be occurring more often, nearly every day I have Scatter open.

Slightly related to https://github.com/GetScatter/ScatterDesktop/issues/243

Since Dec-29 I see 5 proxy vote transactions logged on my account, all from Scatter. To be fair, it could be from two different Scatter installations on two computers, but it is still too often. 

For what it's worth in general not the biggest problem, but for others with low bandwidth these are extra unnecessary transactions that clog up your daily usage.

**Comment by nsjames** [comment]
Should be fixed now, was a problem with timestamps not getting set. 
Can't really do anything about two machines duplicating though as it seems there's no way to get last vote date from the chain aside from searching for recent transactions and that's not really feasible with the multi-network support we have right now. Will have to revisit in the future.
