### ISSUE TITLE
Scatter is unusable on Windows 10 if Docker/Hyper-V is installed

### ISSUE THREAD

**Issue by liamcurry** [GetScatter/ScatterDesktop#245]
On Windows 10 with Hyper-V enabled Scatter can't bind to ports `50005` and `50006` and is unusable:

![annotation 2019-01-02 162850](https://user-images.githubusercontent.com/77758/50613897-25ee0e00-0ead-11e9-82da-f28deb85aa95.jpg)

If I run `netsh int ip show excludedportrange protocol=tcp` I see these ports are being blocked:

![annotation 2019-01-02 162824](https://user-images.githubusercontent.com/77758/50614043-8e3cef80-0ead-11e9-888e-ee46028b6185.jpg)

However if I disable Hyper-V and check again they are unblocked and I can use Scatter as expected:

![annotation 2019-01-02 163853](https://user-images.githubusercontent.com/77758/50614075-a14fbf80-0ead-11e9-95f5-8a44ea6703fe.jpg)

Hyper-V must be enabled to use Docker on Windows. It's easy to enable, here are the instructions: https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v

This is after a fresh reformat with nothing else installed on the machine. I've used Windows/Docker/Scatter in the past just fine, so maybe Microsoft changed something.

**Comment by liamcurry** [comment]
FYI here are steps to work around the issue:

1. If Hyper-V is enabled, disable it and restart your computer.
2. Open a command prompt as administrator.
3. Run the following command:
    `netsh int ip add excludedportrange protocol=tcp startport=50005 numberofports=2`
4. Re-enable Hyper-V and restart your computer.

**Comment by maxocoin** [comment]
Even when I had Hype-V disabled creating a special boot entry with bcdedit . 
`netsh int ipv4 show excludedportrange tcp`
Was still showing those ports as excluded.
I had to disable Hype-V fully for Scatter to work.

Hyper-V comes enabled on all Windows versions but Windows Home, more people is going to have this problem.
I think that Scatter should notify the user if it can't bind to the port

**Comment by nsjames** [comment]
Hyper-V comes disabled and only installed on windows 10, or we'd be seeing **a lot** more issues regarding this. 

It's possible we will be adding a secondary fallback port in the future (already an internal ticket about this) which is 10k ports higher. Apart from that there's nothing much we can do about environment specifics aside from running a shell cmd on installation that reserves those ports for Scatter, but it would persist even after uninstallation causing those ports to be unusable for all other apps even after Scatter is gone ( due to electron ).

**Comment by liamcurry** [comment]
Yeah Hyper-V is disabled by default, and it's only available on Windows 10 Pro (not Home)...but it's required for Docker. So I imagine anyone using Windows + Docker will see this error.

**Comment by maxocoin** [comment]
I was about to create a Feature Request for a second port to listen in case the first is taken.

It is true that not much can be done, but when you start scatter, I think that a warning should come up in case Scatter can't listen on the port 50005,50006.
Right now everything seams fine, but none of the sites detect Scatter.

**Comment by MichealReed** [comment]
I'm encountering this as well even after disabling Hyper-V. Would be great if scatter did not use windows reserved ports.

**Comment by nsjames** [comment]
So I think for one of the next releases we can create a waterfalling system which checks a set of ports on both desktop and scatter-js for availability. Say 50005 or 51005 or 52005 up to 55005 until it finds a port or fails. This might create more time until logins on dapps but will make it stabler.


> Would be great if scatter did not use windows reserved ports.
Those aren't windows or any other OS reserved ports. It isn't even a docker reserved port, it just happens to be one they "claim" as part of a range.

**Comment by coreycottrell** [comment]
here's a wrinkle,had exact same problem,  ran the "netsh int ip add excludedportrange protocol=tcp startport=50005 numberofports=2" but could onlyrun it after i turned scatter off on my desktop.  
HOWEVER, suddenly the BOID dapp request to read the account came through, which is an improvement, 
BUT, 
when i try to stake it hangs on the write-request, scatter doesnt see it.  

and thoughts?

**Comment by coreycottrell** [comment]
error in chrome "
TypeError: Cannot read property 'toFixed' of null
    at stakeTx (3.385979cf28cb13402b7a.js:1)
    at s.<anonymous> (3.385979cf28cb13402b7a.js:1)
    at w (vendor.js:1)
    at Generator._invoke (vendor.js:1)
    at Generator.t.(anonymous function) [as next] (https://app.boid.com/js/vendor.js:1:7553)
    at o (vendor.js:1)
    at a (vendor.js:1)
    at vendor.js:1
    at new Promise (<anonymous>)
    at new e (vendor.js:1)

**Comment by coreycottrell** [comment]
same result on eostoolkit;  it can read scatter to see my account, but freezes on attempt to make a stake request.

**Comment by liamcurry** [comment]
> Say 50005/6 or 51005/6 or 52005/6 up to 55005/6 until it finds a port or fails on max-attempts (we'd need to keep it at around 5 attempts max or dapps would be flooded with uncatchable error messages in console)

A problem with this approach is that it would significantly delay reporting when Scatter is not available (not installed or not open). Right now this takes about ~5 seconds before it fails to connect, but if Scatter has to try a bunch of other ports then I could see that taking a lot longer.

Generally I think Scatter should be a little smarter in detecting the connected state, or more specifically the DISconnected state. I would like for users to know very quickly if they need to install/open Scatter.

One possible solution could be to send a plain HTTP `OPTIONS` request to a local Scatter server before attempting to connect with `socket.io`. If the `OPTIONS` request fails then you know Scatter isn't available and can alert the dapp/user immediately. This should resolve much faster than waiting for the Websocket connection to fail. Also, since the `OPTIONS` requests are pretty lightweight I imagine you could send out a bunch at once without issue. Some pseudocode for how this might work:

```js
pingScatterServer(50005)
    .then(connectToSocketIo)
    .catch(() => {
        Promise.race([
            pingScatterServer(51005),
            pingScatterServer(52005),
            pingScatterServer(53005),
            pingScatterServer(54005),
            pingScatterServer(55005),
        ])
    })
    .then(connectToSocketIo)
    .catch(scatterNotAvailable);
```

**Comment by warrick-eosny** [comment]
This is what fixes it reliably for me every time. Reboot required. 
```
netsh int ipv4 set dynamicport tcp start=50105 num=15431
```

**Comment by coreycottrell** [comment]
tryin this tks

**Comment by coreycottrell** [comment]
tks, no joy.   talking to scatter now.

**Comment by nsjames** [comment]
Scatter 11, with ScatterJS multi-port support now fixes this!
