### ISSUE TITLE
Can't install mac-scatter-10.0.3.dmg on my Mac

### ISSUE THREAD

**Issue by LiorHalfon** [GetScatter/ScatterDesktop#246]
Hi,
I'm trying to run ScatterDesktop on my employer's owned computer,
And I'm getting [this](https://imgur.com/JfgYcou) error:
`
“scatter.app” can’t be opened because it is from an unidentified developer.
Your security preferences allow installation of only apps from the App Store and identified developers.
`

I found a way to run it anyway on [this](https://www.iclarified.com/28180/how-to-open-applications-from-unidentified-developers-in-mac-os-x-mountain-lion) guide, but that's kind of annoying. 😄 

My company's policy probably have a rule to only allow me to run apps from:
> App Store and identified developers

So I guess the solution to this problem is to list ScatterDesktop as an "_identifed developer_", Right?

**Comment by Soleone** [comment]
Yes, that is the solution for now. Annoying but it is no problem. But if you're using a company computer and you have a policy to not activate those kind of unsigned apps then you would be stuck right now on that machine unfortunately.

In the future Scatter will improve this process and get the apps properly signed on all the platforms, but not that straightforward apparently, but definitely on the roadmap obviously.

**Comment by LiorHalfon** [comment]
Awesome, Thanks! 👍

**Comment by nsjames** [comment]
Indeed we are in the process of getting signing keys from microsoft/apple. 
We should be signing the releases in the near future.
