### ISSUE TITLE
Can't send tokens to eos account names when using uppercase letters

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#247]
A user in Telegram today asked:

> I’m getting an error “invalid recipient” in your latest release for an account I’ve verified is accurate via a block explorer. Nothing in support on this, any suggestions?

Turns out the issue was that she was using an uppercase letter in the beginning of the account name. Scatter does not allow that complains with a too generic error:

![image](https://user-images.githubusercontent.com/2923/50661537-6dd66900-0f71-11e9-89c3-5004469d3692.png)

### Suggestion

For EOS account names automatically convert each letter to lowercase. This is what bloks.io does as well if you search for account names there.

**Comment by nsjames** [comment]
Fixed for next release
