### ISSUE TITLE
Fetch Chain ID not working

### ISSUE THREAD

**Issue by DenisCarriere** [GetScatter/ScatterDesktop#25]
🤔 doesn't seem like Fetch Chain ID is working.

Also, I can't Copy-Paste on MacOSX.

Copying letter by letter the chain ID is painful 🤣

- http://api.eosn.io
- https://api.eosn.io

![image](https://user-images.githubusercontent.com/550895/44216401-d8ae1180-a142-11e8-952e-0904fb2e79ff.png)

**Comment by nsjames** [comment]
Update your version macos copy paste fix was about 2 releases ago.

For the chainId, try clicking the dev console button top left and seeing if there's any errors

**Comment by DenisCarriere** [comment]
It now works in 8.7.0 👍
