### ISSUE TITLE
TypeError: e is not a constructor

### ISSUE THREAD

**Issue by mattew2016** [GetScatter/ScatterDesktop#256]
I am having trouble debugging scatter payments.

I have already done the login function and everything works fine. Then I started the payment function by following https://get-scatter.com/docs/examples-interaction-flow and I had a problem.

There is such a sentence in the document (as shown below): `const eos = scatter.eos(network, Eos, eosOptions);`

![scatter](https://user-images.githubusercontent.com/44111182/50808190-6085f980-1338-11e9-9e2f-1281a38e0e74.png)

When the code executes to this sentence, an error is reported (as shown below): TypeError: e is not a constructor

![scatter1](https://user-images.githubusercontent.com/44111182/50809048-654cac80-133c-11e9-9fb1-07f6f5841111.png)

This is the part of my code:

![scatter2](https://user-images.githubusercontent.com/44111182/50809065-709fd800-133c-11e9-869b-075566c546cb.png)

When declaring eosjs, I use `const Eos = require('eosjs'); ` Then use Webpack and Babel to transcode the file.

Scatterjs-core.min.js and scatterjs-plugin-eosjs2.min.js are introduced directly in the html file like this:

```
<script src="https://cdn.scattercdn.com/file/scatter-cdn/js/latest/scatterjs-core.min.js"></script>
<script src="https://cdn.scattercdn.com/file/scatter-cdn/js/latest/scatterjs-plugin-eosjs2.min.js"></script>
```

My eosjs version is 20.0.0.

Finally, repeat: Logging in and getting information is normal, only the payment is problematic, and it is very certain that the code is executing until `const eos = scatter.eos(network, Eos, eosOptions);` The other parts of my code that are not shown are the same code as official documentation.

I have been stuck with this problem for more than a week, and I need help very much. Thank you very much!

**Comment by nsjames** [comment]
So it looks like you're mixing eosjs1 and eosjs2 syntaxes. 
That doc is for eosjs1 ( which is eosjs@16.0.9 )

Check out this boilerplate for eosjs2 syntax https://github.com/GetScatter/Boilerplates/blob/master/scatterjs-plugin-eosjs2/src/views/Home.vue#L160

**Comment by mattew2016** [comment]
> So it looks like you're mixing eosjs1 and eosjs2 syntaxes.
> That doc is for eosjs1 ( which is eosjs@16.0.9 )
> 
> Check out this boilerplate for eosjs2 syntax https://github.com/GetScatter/Boilerplates/blob/master/scatterjs-plugin-eosjs2/src/views/Home.vue#L160

Thank you, bro! I finally got the page out, but there was a new problem. In the transfer page, everything is normal, but after confirmation, it shows `TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))`.

**Comment by nsjames** [comment]
when you instantiate eosjs2 from scatter pass in the `beta3:true` flag. It's not yet documented ( super recent support ), but you can see it here: https://github.com/GetScatter/scatter-js/tree/revamp#using-blockchain-wrappers

**Comment by mattew2016** [comment]
> when you instantiate eosjs2 from scatter pass in the `beta3:true` flag. It's not yet documented ( super recent support ), but you can see it here: https://github.com/GetScatter/scatter-js/tree/revamp#using-blockchain-wrappers

I don't really understand. do you mean by changing `eos = ScatterJS.scatter.eos(network, Api, {rpc}); `to `eos = ScatterJS.scatter.eos(network, Api, {rpc, beta3:true});` ? But I tried it and still showed the same error.

**Comment by nsjames** [comment]
@mattew2016 theres a `beta3:true` flag on the second one. That flag is needed when using `eosjs@20.0.0-beta3` and up

**Comment by mattew2016** [comment]
> @mattew2016 theres a `beta3:true` flag on the second one. That flag is needed when using `eosjs@20.0.0-beta3` and up

I'm using eosjs@20.0.0-beta2

**Comment by nsjames** [comment]
As, so turn off that flag. Or just update to beta3

**Comment by mattew2016** [comment]
> As, so turn off that flag. Or just update to beta3

Thanks, bro! The problem solved.
