### ISSUE TITLE
Can't disable re-proxy without actually submitting a transaction

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#258]
A user reported that he was unable to disable the re-proxy once enabled. Unsetting it does not stick unless you actually press the Set Proxy button at the bottom which ends up issuing a new transaction to the blockchain.

![image](https://user-images.githubusercontent.com/2923/50925375-2db73080-1420-11e9-82c9-0f78393066e2.png)

### Suggestion

Makes sense to me that Scatter should remember the setting without the user having to issue another proxy vote transaction.

**Comment by nsjames** [comment]
Added a way to remove proxy
