### ISSUE TITLE
Scatter 10.1: Unable to log into Chintai 

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#264]
I can not replicate this issue, it is working for me on OSX in Safari. But I saw two users unable to log in to https://eos.chintai.io with latest Scatter Desktop 10.1.

No particular error in the Javascript console, just general "unable to find Scatter" messages.

### User A

On Ubuntu, tried Chrome und Firefox, restarting PC didn't fix the problem:

He confirmed that chintai worked fine using previous Scatter Desktop 10.0.3. Also other sites work with Scatter Desktop 10.1.

![telegram-cloud-file-2-257913429-56349--5389163002092551272](https://user-images.githubusercontent.com/2923/51203325-c80aee80-18ce-11e9-996d-f0c8deb11179.jpg)

### User B

On Windows 7 64 bit, tried Chrome and Chrome Incognito mode

![telegram-cloud-file-4-446614721-481450-8563072244854832381](https://user-images.githubusercontent.com/2923/51203311-bfb2b380-18ce-11e9-8106-3e237a19099e.jpg)

![telegram-cloud-file-2-255415915-108133--6527413289045099406](https://user-images.githubusercontent.com/2923/51203318-c3463a80-18ce-11e9-936c-2f4e3faa0580.jpg)

**Comment by nsjames** [comment]
Hmm. I also can't seem to reproduce this.
I'm thinking it might be some `appkey` issue as the latest desktop version cleaned out all appkeys that werent in use anymore but were staying persisted in the user's scatter. I think we might have to wait for some more reports about this to try and find a pattern.

**Comment by Soleone** [comment]
I also feel like it might be related to appkey and the popup required to confirm first.

I am seeing more reports, even on newest version 10.1.1

**Comment by nsjames** [comment]
I think that possibly the easiest way to check if its lingering `appkeys` causing the issue would just having a user destroy their Scatter data and seeing if they can then connect to apps successfully since they would simply no longer have any `appkeys`. I'm gonna try to grab someone from chat with the issue and try that.

**Comment by nsjames** [comment]
Cleaning tickets for Scatter 11 testing release (makes this ticket no longer relevant)
