### ISSUE TITLE
Can't create backup -Desktop

### ISSUE THREAD

**Issue by CryptoHusker2017** [GetScatter/ScatterDesktop#266]
Built a new windows workstation and I'm not allowed to create a backup from old PC to open existing account on new PC.

**Comment by nsjames** [comment]
Can you walk me through exactly what's happening?

Also, try opening the console (f12) in Scatter and seeing if there's any error there.

**Comment by nsjames** [comment]
Cleaning tickets for Scatter 11 testing release (makes this ticket no longer relevant)
