### ISSUE TITLE
scatter.authenticate(12_CHAR_RANDOM_STRING) how to verify in the new version

### ISSUE THREAD

**Issue by yzhsuper** [GetScatter/ScatterDesktop#267]
I use the "authenticate" function, 
it's need "12_CHAR_RANDOM_STRING", i give sign_param="123456789012"
it's return sign data.
now, i want to verify the sign data, but failed.

The ScatterDesktop version is 10.1.0.
But my old version(9.6.0) is ok, 

Where does the new version change?

**Comment by nsjames** [comment]
Check out this testcase to see how to validate authenticate
https://github.com/GetScatter/scatter-js/blob/master/mock-sites/vanilla-eos/index.html#L137
