### ISSUE TITLE
Scatter Desktop doesn't work when configured SOCKS Proxy

### ISSUE THREAD

**Issue by jiangweifeng** [GetScatter/ScatterDesktop#269]
run command line: ssh -D 1080 IP/URL and configure the SOCKS proxy as localhost 1080, and scatter desktop doesn't work, but scatter chrome extension works.. 

Can anyone help? any changes / settings can be made in order to make scatter desktop work under SOCKS proxy?

**Comment by nsjames** [comment]
It's possible that we might need to add proxy support directly into Scatter. 
I see you closed this though, did you find a workaround?

**Comment by jiangweifeng** [comment]
with the latest version of scatter desktop, it works most of the time when I turn on proxy. So, issue closed.
