### ISSUE TITLE
Make it more obvious which EOS account is about to sign a transaction

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#27]
![image](https://user-images.githubusercontent.com/2923/44231273-8df4bf80-a16b-11e8-8a36-8ee70d75e0eb.png)

In general I would like to see the following information quickly glanceable as a priority:

1. Which eos account am i currently using
2. Which account(s) am I sending a transaction to
3. Which action am I calling
4. Parameters of that action

Other:

A badge for (endorsed) mainnets could be nice to quickly differentiate between test and live mode.

**Comment by nsjames** [comment]
763a1a0e28f4971002ef3aed50e3b29573b90751

**Comment by nsjames** [comment]
58d66aa8955070f71ed5398f70f28d46bcd9ccd5
