### ISSUE TITLE
ApiService.js (What is the value of the origin)

### ISSUE THREAD

**Issue by yzhsuper** [GetScatter/ScatterDesktop#270]
https://github.com/GetScatter/ScatterDesktop/blob/10.1.0/src/services/ApiService.js#L422.
my local host: 172.16.16.20

sign_data = '072883022636';
toSign = '172.16.16.20';

`
const isHash = request.payload.hasOwnProperty('data') && request.payload.data && request.payload.data.length;
const toSign = isHash ? request.payload.data : origin;

// Prevention of origins being able to send data buffers to be
// signed by the identity which could change to a real balance holding
// key in the future.
const data = Hasher.unsaltedQuickHash(
	Hasher.unsaltedQuickHash(toSign) +
	Hasher.unsaltedQuickHash(request.payload.nonce)
);
`
i call the function scatter_core.authenticate(sign_data, toSign)
and scatter_core.authenticate(sign_data)

the return data is different, why?

**Comment by nsjames** [comment]
If you're passing in your own `location.hostname` then you can just call `ScatterJS.authenticate(nonce)` as your `location.hostname` will be auto-fed into it. 

On the other side of things you need to do the same calculations that Scatter is doing internally.
Check out this test-case: https://github.com/GetScatter/scatter-js/blob/master/mock-sites/vanilla-eos/index.html#L137

**Comment by yzhsuper** [comment]
> If you're passing in your own `location.hostname` then you can just call `ScatterJS.authenticate(nonce)` as your `location.hostname` will be auto-fed into it.
> 
> On the other side of things you need to do the same calculations that Scatter is doing internally.
> Check out this test-case: https://github.com/GetScatter/scatter-js/blob/master/mock-sites/vanilla-eos/index.html#L137

yes, i know that.
i just hava a question,
const toSign = isHash ? request.payload.data : origin;

when the isHash is false, then toSign=origin, what is the value of origin?
i an new to nodejs, i can not find the "origin" variable where to define it in the file "ApiService.js "

**Comment by nsjames** [comment]
`origin` is actual `location.hostname` which is available in any browser environment.

**Comment by Jeiwan** [comment]
Just a hint to anyone coming across this issue: `origin` is `file://` when using Scatter Desktop.
