### ISSUE TITLE
Uncaught Error: listen EACCES 127.0.0.1:50005

### ISSUE THREAD

**Issue by maxocoin** [GetScatter/ScatterDesktop#271]
I upgraded to Scatter 10.1.1  and I can't login using Firefox or Chrome.

When I open Scatter's console I see:
```
Uncaught Error: listen EACCES 127.0.0.1:50005
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1334:19)
    at listenInCluster (net.js:1392:12)
    at doListen (net.js:1501:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183 Uncaught Error: listen EACCES 127.0.0.1:50006
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1334:19)
    at listenInCluster (net.js:1392:12)
    at doListen (net.js:1501:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
I disabled the firewall just in case but I see the same issue.
Running on Windows 10

**Comment by Soleone** [comment]
It sounds like on your machine the port 50005 might already be in use by another program.

Could you try using the Resource Monitor app in Windows 10 to try to figure out if you see something that is using port 50005 next time you see this error? https://stackoverflow.com/a/23718720

**Comment by maxocoin** [comment]
No, I already checked that 
![image](https://user-images.githubusercontent.com/30597258/51414380-2d2e4080-1b6a-11e9-9d7a-8e7bb3238433.png)

**Comment by maxocoin** [comment]
I disabled the antivirus and the firewall, always the same error

**Comment by nsjames** [comment]
Are you running docker?

I see you're on windows and for windows the port being used isn't the only thing, it could also be reserved.
Try putting `netsh int ipv4 show excludedportrange tcp` into cmd/console and seeing if the ports 50005 and 50006 are included in a reserved range there.

**Comment by maxocoin** [comment]
nsjames, thank you.
I didn't know about that!!!
Yes, they are in the reserved range:
    50001       50010
Not what?
Un-reserve those ports? Force the use of those port even when they are reserved?
Or is there a way to change the port that Scatter is listening to (and won't that break the webs finding scatter?
Cheers
 JD

I think that this should be detected by scatter and display some work around

**Comment by nsjames** [comment]
@maxocoin You can try manually releasing them by altering and using this command:

`netsh int ip delete excludedportrange protocol=tcp startport=49998 numberofports=99`

Otherwise you'll have to find the application that is using those ports and disable/uninstall it.
Sadly you can't change the ports that are being listened to since the apps define that port inside the scatter-js library. Without a way to have an initial connection then there's also no way to find a way to change ports either since it would effectively make scatter into a port-scanner.

**Comment by maxocoin** [comment]
Thank you.
It gives me access denied :-(

```
C:\WINDOWS\system32>netsh int ipv4 delete excludedportrange protocol=tcp startport=50001 numberofports=10
Acceso denegado.
```
Any tips for find out the software that reserved the ports?

**Comment by maxocoin** [comment]
Duplicate of ##245
I disabled hyper-V restarted and Scatter started to work

**Comment by 4Ykw** [comment]
Maybe in the future, we can set this to use local6 instead. There will be extra goodness, protection in that area and it will not be a problem for Windows damn stupid default way of reserving ports.
