### ISSUE TITLE
The desktop version of scatter is much slower than the chrome extension

### ISSUE THREAD

**Issue by shareven** [GetScatter/ScatterDesktop#273]
The desktop version of scatter is much slower than the chrome extension. The scatter extension call contract takes only 1 second, but the desktop version takes more than 10 seconds.
Can u solve this issue?

**Comment by Soleone** [comment]
I can not replicate this problem. In fact Scatter Desktop is normally much faster than the Chrome extension. So something weird is going on on your side.

* Which browser and operating system are you using?
* Which country are you in?
* Are you using a VPN?

**Comment by jianhuaixie** [comment]
@Soleone 
![image](https://user-images.githubusercontent.com/8100174/51453433-689f5980-1d7a-11e9-8c55-5478b20669ba.png)
look the image,when I request ,get_abi ,get_info and get_block is good,but the chrome browser call the Scatter-Desktop is too slow,sometimes ,need 1-2 minutes.
So, I doubt that the browser call the Scatter-Desktop is not stable.

**Comment by jianhuaixie** [comment]
@Soleone 
![image](https://user-images.githubusercontent.com/8100174/51453538-e2374780-1d7a-11e9-994b-4debdf93e5f5.png)
Sometimes ,the request is also too slow.like this,get_abi need 15.99s, the request url is : https://jungle-node.mywish.io/v1/chain/get_abi

**Comment by balboah** [comment]
I've noticed a long delay for about 5-15s on most interactions as well (Sweden, no VPN, Chrome, macOS)

**Comment by nsjames** [comment]
Cleaning tickets for Scatter 11 testing release (makes this ticket no longer relevant)
