### ISSUE TITLE
TRX tokens are not showing up in accounts

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#275]
We've had a bunch of complaints about this so I investigated. If you send or exchange tokens for TRX, they go to the blockchain and do the transaction correctly. However inside of Scatter you never see the update.

I think that there is a problem reading the Tron blockchain for account balances.

You can see on Tronscan the scatterrefer account has transactions that do not show up in the account:
https://tronscan.org/#/address/TJfGpJvuVXErpu5MVZBNUNZvrsGtPR4pKg

**Comment by nsjames** [comment]
I seem to see balances in mine. I wonder if it's just missing some since the Tron node changes recently.
can you send me like 1TRX to TF2quv1hTipcZ8FJ8FRsXXLSiJ1C15dqkW and then paste the TXID here?

![image](https://user-images.githubusercontent.com/10360675/51521408-3d2a7680-1e2f-11e9-90bb-698d15459f30.png)

**Comment by nsjames** [comment]
Wooo! Then we don't have to search :P
After we finish some of the more pressing bugfixes lets work on a solution for this for the next patch release so we can put the bug to bed.

Adding an internal ticket and closing this out for now.

**Comment by iamsurya** [comment]
Was this fixed? I created a wallet in Scatter today and sent some TRX to test. Tronscan shows the wallet amounts correctly but Scatter still shows 0.

**Comment by nsjames** [comment]
It **is** fixed, but isn't released into a build yet.

**Comment by thetokendude** [comment]
I am having the same problem... Please help?

https://tronscan.org/#/address/TJFvMHNYDMyfz9Jue3QT14axFLRVbsZdQY

**Comment by nsjames** [comment]
Already fixed for next build. You can get the test build from releases and validate that it's already showing up in Scatter 11

**Comment by jcalfee** [comment]
Super, I'll look forward to v11.  I'm thinking this will also fix Tron custom-token balances like BTT.

**Comment by AKEK114** [comment]
I have issue of missing TRX (Approx 25k) from my Windows Tron Wallet. This I came to know once I tried to check in few weeks time yesterday.  My wallet receive address is TDSRex4NF5egmpZdCUhMXjBvt77BGpAvbV

Can anyone help why TRX are not shown or how to recover? I tried few times with TRX customer service and feedback but ALAS they are really not in mood to help apparently .. at least as of now.

**Comment by ramijames** [comment]
> I have issue of missing TRX (Approx 25k) from my Windows Tron Wallet. This I came to know once I tried to check in few weeks time yesterday. My wallet receive address is TDSRex4NF5egmpZdCUhMXjBvt77BGpAvbV
> 
> Can anyone help why TRX are not shown or how to recover? I tried few times with TRX customer service and feedback but ALAS they are really not in mood to help apparently .. at least as of now.

Update to 10.2.0:
https://github.com/GetScatter/ScatterDesktop/releases/tag/10.2.0-prerelease

**Comment by thetokendude** [comment]
Find version 11 in Github  for scatter.
That worked for my Trx
 👍🏽

**Comment by AKEK114** [comment]
Thx for help. Can u explain how exactly by downloading Scatter 11 , I can
get TRX back from my TRON WINDOWS desktop wallet? Sorry I am novice and
requires some instructions.  Thx

**Comment by ramijames** [comment]
The TRX tokens are not inside of Scatter, they are on the Tron blockchain. Any Tron enabled wallet will give you access to those tokens.

**Comment by serggut1981** [comment]
BALANCE ON TRON Wallet Desktop IS NOT DISPLAYED, what to do? wallet address
TBqqB3Y8rXLmiZXdAxktaYBHa5A31wMgvc

**Comment by serggut1981** [comment]
Can u explain how exactly by downloading Scatter 11 , I can
get TRX back from my TRON WINDOWS desktop wallet? Sorry I am novice and
requires some instructions.  Thx

**Comment by nsjames** [comment]
Just download Scatter 11 and import your tron key. That's it.

**Comment by nsjames** [comment]
Yup. When you import your private key it will link it into Scatter and fetch balances for it.

**Comment by serggut1981** [comment]
how many characters should be on the throne in a private key?

**Comment by serggut1981** [comment]
tronwatch 128 characters? Is there a link to the video? or instructions? I'm sorry I'm new

**Comment by nsjames** [comment]
Usually 64.

And example key would be `0bd943bfb8c19c244dae272f6506ee2b448d847d52e137132779b8b087bccf55`
(Don't use this key, of course, as it's now burned)

**Comment by serggut1981** [comment]
Do I have a screen shot of 128 characters? can it be?

**Comment by nsjames** [comment]
Some wallets allow for any length keys, you could try it. Might not work in Scatter though as we enforce specifics for key lengths to protect users.

**Comment by serggut1981** [comment]
Why are tronwatch removed from the official site?

please tell me what wallets?

I remember the code from the wallet, and it gives the private key 128 characters, and 24 words are also correct

but when importing to the tronlink, the wrong wallet is issued

please tell me what support to write?

**Comment by serggut1981** [comment]
NEW CREATED WALLET IMPORTED IN THE SCATER 11 IN TRONLINC

**Comment by iamsurya** [comment]
@serggut1981 You're new to github so I'd like to be kind when I say this, but your comments are absolutely against how github issues work. I say this so that you don't repeat this behavior in other github projects.

Github issues are used by developers to discuss bugs in software, and are very specific. While you had questions on your TRX tokens, it was fine, however you later just moved to turn this issue into a tech - support thread, i.e. hijacking the thread. And I'm not sure what the point of your last comment was, or why it is in all caps, which usually means you are shouting (on the internet).

**Comment by serggut1981** [comment]
I am sorry, I do not know who can help me

**Comment by ramijames** [comment]
Please send a request to support@get-scatter.com and we will help you resolve this there.

**Comment by AKEK114** [comment]
Hi, May be this helps. You can recover your missing TRX as fol:

1.  Install Chrome extension for Tronlink on your Chrome browser
2.  You may have to enter new password for Tronlink once installed
3.  Import your seed (secret words ) and user name you already had.

This shall resolve your issue .

Regards

Ahsan
