### ISSUE TITLE
User is reporting that EOS -> BNT transaction gets lost

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#276]
I have a user who tried to exchange 90EOS and says that the BNT never showed up in their account:
https://bloks.io/transaction/d83d18bd4c19003fc8b3acffd7aaf4009c5b0b0f502406715712119cd0472d9c

It ended up in account "bntbntbntbnt" and I can't tell whether they put that in the "account to" field or if there is something wrong on our end. We have to check it.

**Comment by nsjames** [comment]
Discussing internally.
