### ISSUE TITLE
Atomic swaps sometimes don't show up in exchange

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#277]
Not sure why, but atomic swap options are not showing up. Not seeing any errors in console. Selected from token is EOS.

<img width="1289" alt="screen shot 2019-01-19 at 8 08 01 pm" src="https://user-images.githubusercontent.com/814302/51430567-f3227480-1c25-11e9-827d-8cd10e881bb0.png">

**Comment by nsjames** [comment]
This happens when the bancor network's API is down for maintenance or just temporarily down.

**Comment by nsjames** [comment]
Cleaning tickets for Scatter 11 testing release (makes this ticket no longer relevant)
