### ISSUE TITLE
RE: Token Exchange

### ISSUE THREAD

**Issue by jiangh77** [GetScatter/ScatterDesktop#278]
When exchanging tokens inside Scatter Wallet, is the exchange fee charged in EOS or other tokens?

Thank you

**Comment by nsjames** [comment]
It completely depends on the token and the exchange type.

When using EOS to other alt-EOS tokens it's free using Bancor.

When exchanging base tokens or stable tokens (EOS, ETH, TRX, BTC, TUSD, etc) then the exchange service we are using take a small fee (I think it's 0.01%)
