### ISSUE TITLE
No write access for backups hangs Scatter

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#279]
It looks like if the user selects a folder which Scatter does not have write access to, it hangs the app and won't allow the user to continue.

I think there are two things we need to do to handle this:

1. Check if the user's selected folder has write access
2. If it fails on login (creating the json file) then prompt the user to select a different folder.

![stuck](https://user-images.githubusercontent.com/814302/51468440-a6e74980-1d77-11e9-90d6-79a02f4ef2da.jpg)

**Comment by nsjames** [comment]
Fixed for next release
