### ISSUE TITLE
No way to exchange TUSD to another token

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#281]
Whilst most swaps work great in scatter I noticed the EOS to TUSD one works nicely too but theres no TUSD token button etc under the user's main ETH address nor in the token exchange so no ability to exchange back from TUSD to EOS. Will have to send the old Myetherwallet way. Thanks pal.

**Comment by nsjames** [comment]
Fixed partially for next release. 
It adds unknown tokens (exchanged, but not tracked) when exchanging to them, but had a flipped boolean there which prevented it from being added.

However, if a user re-builds their scatter from scratch they will not see their balances. We should start looking into cross-blockchain token APIs so we can cache Ethereum and Tron tokens the same way we do for EOS.

**Comment by ramijames** [comment]
Ok.

We also had a user recently ask about Tron tokens besides TRX.

**Comment by nsjames** [comment]
The tron tokens which are built-in to the tron system ( they have their own internal API cacher system ) show up, but the TRC20 tokens don't yet. Pegged for a future release.
