### ISSUE TITLE
Laggy popups

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#282]
I've noticed a distinct increase in the time that it takes to show and render a popup for login or other transactions. I'm not sure whether it was after 10.0.3 or before. At this point it takes upwards of ten seconds sometimes.

**Comment by nsjames** [comment]
If it was an added second, i'd say that has to do with moving the seed from the renderer to the main process. But 10 seconds sounds more like a networking issue. 

I'm going to change the nodes under the load-balancer and see if that speeds things up a bit.

**Comment by ramijames** [comment]
I also see the popup show a white screen and a few seconds later the actual popup is rendered. Not sure what's up with that.

**Comment by nsjames** [comment]
This is on osx right?

**Comment by ramijames** [comment]
Yes, OSX Mojave (10.14.1)

**Comment by nsjames** [comment]
Cleaning tickets for Scatter 11 testing release (makes this ticket no longer relevant)
