### ISSUE TITLE
Intermittent connections

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#283]
It's a problem that I've noticed and users are complaining about. If you have Scatter open, and open a dapp sometimes it will "see" Scatter and sometimes it will not. I just had this happen with https://eosbet.io/

I have ghostery installed and maybe that is causing issues. On Firefox.

**Comment by nsjames** [comment]
Did you happen to get any console logs when the connection issue occurred? I'm having issues reproducing this and need some error messages to try and pinpoint the issue.

**Comment by ramijames** [comment]
It's hard to reproduce. Not really sure what is causing it. In Scatter's console I don't see any issues. In the dapp's console I see dapp specific errors like "scatter not found".

Maybe a websockets issue? Is it possible something else is using the same socket?

**Comment by ramijames** [comment]
User just sent this: 
![2019-01-22 09 41 40](https://user-images.githubusercontent.com/814302/51519549-fab26b00-1e29-11e9-83a0-378e032467bb.jpg)

**Comment by nsjames** [comment]
So, the above error ( which we talked about on telegram ) looks like an issue with the certs that the node eospoker.win is using.

**Comment by str** [comment]
I have the same problem with Firefox. Sometimes it signs the transaction, sometimes it doesn't. 

![image](https://user-images.githubusercontent.com/123817/54466637-30971000-4746-11e9-85c4-48561da464d3.png)

No resposne at all in Firefox's console. Nothing in the Scatter console.

**Comment by nsjames** [comment]
Cleaning tickets for Scatter 11 testing release (makes this ticket no longer relevant)
