### ISSUE TITLE
Can't get scatter to work at all with eospoker.win

### ISSUE THREAD

**Issue by renkcub** [GetScatter/ScatterDesktop#284]
Stopped working desktop version even after rolling back to Version 10. Doesn't work on IE or Chrome. If anyone can get it to work please comment.

**Comment by nsjames** [comment]
I need some more information about this like console logs from both the web app and Scatter. 
You can access both of them by pressing f12 either in Chrome on the web app or in Scatter and then clicking the "console" tab.

**Comment by renkcub** [comment]
game started working agin. please close.
