### ISSUE TITLE
When doing multiple exchanges, the receiving token should default to last token used

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#289]
<img width="1246" alt="screen shot 2019-01-23 at 9 46 31 pm" src="https://user-images.githubusercontent.com/814302/51632722-a954c980-1f58-11e9-8915-7ce93c476637.png">

**Comment by nsjames** [comment]
Cleaning tickets for Scatter 11 testing release (makes this ticket no longer relevant)
