### ISSUE TITLE
Signing for other authorizations

### ISSUE THREAD

**Issue by Khazius** [GetScatter/ScatterDesktop#29]
It would be great if you could sign with one identity for other authorizations.
This is typically for multisig.

Say you have a transfer for bankcorp
bankcorp@active [threshold 1] = {user1@active [weight 1], user2@active [weight 1]}

The authorization for the transfer must be bankcorp@active, but it must be signed by user1@active.

Under current scatter you will get a "repull identity error"

**Comment by Khazius** [comment]
* Is there a reason Scatter wont use the currently linked ID from ```scatter.getIdentity```?
* ```eosjs``` supports this natively in the sense that you can use any KeyProvider you want regardless of the authorization you specifiy

**Comment by nsjames** [comment]
> Is there a reason Scatter wont use the currently linked ID from scatter.getIdentity

It does actually. When that error is throw it means that the accounts that are permissioned to the domain/origin ( identity permissions ) don't include an account specified in the authorizations array passed into eosjs.

**Comment by nsjames** [comment]
I'm going to close this with a reference to this [newer ticket](https://github.com/GetScatter/ScatterDesktop/issues/52) as that's the only part of it which should be revisited.
