### ISSUE TITLE
Shitcoins should be below altcoins I can exchange

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#290]
I would also love a way to bulk liquidate all my shitcoins

<img width="1241" alt="screen shot 2019-01-23 at 9 49 34 pm" src="https://user-images.githubusercontent.com/814302/51632805-cd180f80-1f58-11e9-8bdc-003961ebb596.png">

**Comment by nsjames** [comment]
"Shitcoins" is subjective.
Lots of people think EOS and ETH are shitcoins.

For the ordering of the list though it's based on your value of tokens in the native fiat currency, but system tokens are always on top (eth, eos, trx, etc).

You can also use `^` in the searchbar to instead order them by token quantity.

**Comment by maxocoin** [comment]
I think that the notion that all the coins with an exchange pair should go before the coins without one is a good default
