### ISSUE TITLE
Prevent scams trying to change permissions

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#291]
As we saw in the latest Telos scam, users sometimes are not aware how devastating changing permissions can be.

This should be mostly solved once RIDL comes online and the community can mark these contracts or websites as scams. But there will still be "early adopters" that wont have any community warning yet and fall prey.

And I am not sure how long it will still take until RIDL is in a state to have prevented this actual use case.

A Telegram user who initially asked for 2FA when changing permissions in Scatter also said:

> A change of auth should never be a single button push

I kind of have to agree with that.

### Suggestion

![image](https://user-images.githubusercontent.com/2923/51637042-ba85e200-1f28-11e9-969c-9ba89ee38899.png)

**That popup could show some sort of warning and require additional confirmation before going ahead and changing the permissions.**

To generalize a bit maybe there could be a (black)list of actions that shows this generic messaging, maybe even as a key value list where a custom message is displayed for each "dangerous" action.

### Complications

The quick fix would be to just implement this for `updateauth` action on eosio base blockchain itself, better than nothing.

A more generic approach would be to support eosio sisterchains (which might have different account names), I don't think it would make sense to have to extend to other blockchains like ETH or Tron.

**Comment by nsjames** [comment]
The version that was just released (10.1.2) now has warnings in the signature popup for "updateauth".

![image](https://user-images.githubusercontent.com/10360675/51668063-0f2d6980-1fca-11e9-8581-6315113c6e07.png)
