### ISSUE TITLE
10.1.2 can't sign any transaction

### ISSUE THREAD

**Issue by plouto5** [GetScatter/ScatterDesktop#293]
Currently running Manjaro and I can no longer sign transactions since switching from 10.1.1 -> 10.1.2  
Tried both ledger account and non ledger(scatter) account. 
On eostoolkit, the pop comes up on both accounts ( Sending.... scatter should appear shortly ) permanently sits there till i close it. 

I have tried opening the old 10.1.1.app and it does the same thing still. Any suggestions greatly appreciated.

Edit* 
Have tried multiple browsers now. Still not working.

**Comment by nsjames** [comment]
Any errors in the app console or scatter console?

**Comment by nsjames** [comment]
Looks like network issues. Can you try changing host for mainnet in Scatter's network settings back to `nodes.get-scatter.com`?

Also, post a screenshot of your mainnet network

**Comment by plouto5** [comment]
It was a network issue... Thanks for your time Nate and keep up the great work!

**Comment by nsjames** [comment]
I'm thinking perhaps we should issue clearer errors messages there and do network validity tests so that it's easier to debug these issues.

I'll add a ticket about it for next release 👍
