### ISSUE TITLE
Feature Request: ability to copy / select text in the transaction confirmation popup

### ISSUE THREAD

**Issue by acoutts** [GetScatter/ScatterDesktop#294]
It would be nice to be able to highlight and copy text from the transaction confirmation dialog- especially on the JSON screen.

![screen shot 2019-01-25 at 7 41 48 am](https://user-images.githubusercontent.com/9597207/51746637-d1d1e600-2074-11e9-92e5-75eaf4705726.png)

**Comment by nsjames** [comment]
I think in general the lack of ability to copy is annoying and "over-engineering".
I've removed the css that causes it for the entire app. 
Will be available from next release.
