### ISSUE TITLE
Suggesting new network from scatterjs doesnt require confirmation

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#296]
It seems that when using `suggestNetwork` with ScatterJS the network will just be added to Scatter Desktop without any confirmation popup showing up. Unless I am misunderstanding something this could 

@jonericcook used the code below, that as I understand it immediately got Scatter searching this new network for all imported public keys and then resulted in this dialog:

![image](https://user-images.githubusercontent.com/2923/51808723-aeba5880-2265-11e9-867d-2e2e8573b700.png)

```
ScatterJS.connect(
        'test',
        { network }
      ).then(connected => {
        if (!connected) return console.error('no scatter')
        ScatterJS.login().then(id => {
          if (!id) return console.error('no identity')
        })
      })
```

> and the network parameters is nodeos running locally
> here was no popup but now the network is in the drop down

### Suggestion

Shouldn't there be a popup whenever an app suggests a new network for Scatter to let the user confirm they want that network added?

If not what's stopping a malicious site to spam all connected Scatter users' network list?

As an anecdote I was a bit surprised myself that for adding the BOS chain the official instructions were just to visit https://bos.bloks.io, click on Login and then Scatter would immediately be able to pop up with the login dialog for each new account on that blockchain, without me having to confirm adding that BOS network first.

**Comment by nsjames** [comment]
Actually, the popup was taken out a while ago and replaced with time constraints, so 1 network every 24 hours from the same origin.

The reasoning behind the change is an onboarding flow crisis. When creating a new account on a side chain the process is as follows:

- `suggestNetwork(network)`
- `hasAccountFor(network)`
- `getPublicKey(blockchain)` - **popup**
- dapp creates account for user
- `linkAccount(account, network)`
- `login(...)` - **popup**

It used to be that suggestNetwork, and linkAccount both had popups, but as sidechains started becoming more and more popular we decided that 4 popups for account creation was just ridiculous.

**Comment by nsjames** [comment]
> As an anecdote I was a bit surprised myself that for adding the BOS chain the official instructions were just to visit https://bos.bloks.io, click on Login and then Scatter would immediately be able to pop up with the login dialog for each new account on that blockchain, without me having to confirm adding that BOS network first.

The real question here is, how did that feel?

**Comment by nsjames** [comment]
This does bring up another point though, perhaps we can just merge `suggestNetwork` into `login/getIdentity` and use the single popup for both cases.

**Comment by Soleone** [comment]
> The real question here is, how did that feel?

Yea, I won't lie, it felt pretty good :D
