### ISSUE TITLE
Unclear Language on New Account Creation / Resource Loading Screens

### ISSUE THREAD

**Issue by patriciaparkinson** [GetScatter/ScatterDesktop#297]
It's not intuitive to new users the purpose of this resource loading screen. Would be beneficial to be more explanatory on the purpose of this step and options to make the transfer. The error message "Transaction is not yet irreversible" is also confusing to new users (and a double negative).

**Comment by nsjames** [comment]
> It's not intuitive to new users the purpose of this resource loading screen. Would be beneficial to be more explanatory on the purpose of this step and options to make the transfer. 

Do you think a kind of "wizard" flow be more appealing?

-------------

for the second part, I changed the error from our backend to: "Transaction is not yet irreversible. You must wait at least 3 minutes for the transaction to be included into the blockchain.". How would it be a double negative though?

**Comment by nsjames** [comment]
Cleaning tickets for Scatter 11 testing release (makes this ticket no longer relevant)
