### ISSUE TITLE
Version 9.6.1 (9.6.1) - Password Incorrect?

### ISSUE THREAD

**Issue by bensig** [GetScatter/ScatterDesktop#300]
I know my password is correct, it worked a few minutes ago. I added a new network and the app froze, now it will not unlock.

**Comment by nsjames** [comment]
It looks like perhaps a bit of data corruption occurred when the app froze. Likely it was trying to save save when it froze which corrupted the data. You should have a recent backup file in your automatic backups folder that you selected. Destroy your current Scatter (press "d" on the login screen 10 times) and the import your most recent backup, which should be right before the corruption.

**Comment by bensig** [comment]
Ok, I tried this the other day. I only see one backup. When I restore it, it also says "bad password."

**Comment by nsjames** [comment]
Cleaning tickets for Scatter 11 testing release (makes this ticket no longer relevant)

**Comment by nsjames** [comment]
There's a fallback data registry which handles corruption now.
