### ISSUE TITLE
Ubuntu: Can't import Ledger keys if Ledger Live is open

### ISSUE THREAD

**Issue by acoutts** [GetScatter/ScatterDesktop#301]
It seems like only one program can access the Ledger at a time. The error below was ambiguous and didn't let me realize right away what I was trying to do with both programs open. Perhaps there's a way to warn the user to ensure Ledger Live isn't open also.

![screenshot from 2019-01-31 13-23-21](https://user-images.githubusercontent.com/9597207/52075926-87140a80-255b-11e9-8be0-4e49e1a031f0.png)

After closing Ledger Live, Scatter can communicate with the Ledger without issue but only after closing and re-opening the EOS app on the Ledger.

**Comment by Shabbypenguin** [comment]
Experiencing this on Windows 10 Insider Preview 10.0.18362.30 (19h1_release) amd64 2019-04

**Comment by nsjames** [comment]
This is indeed a problem with node-hid and can't be fixed by Scatter. Sorry guys.
