### ISSUE TITLE
When importing an EOS key assigned as only the Owner key to an account, Scatter displays it as an active key

### ISSUE THREAD

**Issue by acoutts** [GetScatter/ScatterDesktop#302]
It's possible this means active in another sense and I've understood it wrong.

![screenshot from 2019-01-31 13-28-37](https://user-images.githubusercontent.com/9597207/52076210-2c2ee300-255c-11e9-9c3c-9fed8f33cc6f.png)

**Comment by nsjames** [comment]
That shouldn't be the case actually. 
I also can't seem to reproduce this locally. When I import a key for mainnet that is only an owner, it only shows the owner tag above the account name.

![image](https://user-images.githubusercontent.com/10360675/52527842-0a5dfa80-2cd8-11e9-9285-c733fc55c278.png)

**Comment by nsjames** [comment]
Cleaning tickets for Scatter 11 testing release (makes this ticket no longer relevant)
