### ISSUE TITLE
10.1.2 missing network tab

### ISSUE THREAD

**Issue by jcalfee** [GetScatter/ScatterDesktop#303]
I don't see all networks in this scatter tab.  Shouldn't this have "Your Networks" and "Known Networks" udner the title "Networks"?

![image](https://user-images.githubusercontent.com/204121/52370791-6cd5a300-2a19-11e9-8a30-f8fd34a4e897.png)

As a result, my portfolio shows only EOS and TELOS but because I can't add them from Known Networks, it is missing others like BOS and EOS Force.  I tried restoring from a backup.

This is the only thing in the console, probably unrelated:
![image](https://user-images.githubusercontent.com/204121/52371048-19b02000-2a1a-11e9-8945-fb071c8a2f81.png)

If I try to add them from that screen, selecting something in the drop-down then clicking Add, resets the form:
![image](https://user-images.githubusercontent.com/204121/52371210-86c3b580-2a1a-11e9-91c1-39507a35e896.png)

**Comment by jcalfee** [comment]
linux-scatter-10.1.2-x86_64.AppImage
Debian GNU/Linux 9 (stretch)

**Comment by nsjames** [comment]
Cleaning tickets for Scatter 11 testing release (makes this ticket no longer relevant)
