### ISSUE TITLE
Feature request: Key name displayed in the login screen along with the account name

### ISSUE THREAD

**Issue by maxocoin** [GetScatter/ScatterDesktop#304]
Hi,
With all those confuse account names generated at the network lunch, I have a hard time differentiating the different accounts when the screen to login into a "Dapp" is presented.

I would love to see in brackets, next to the account name, the   "key name" I gave to it when I imported the private key

**Comment by nsjames** [comment]
Cleaning tickets for Scatter 11 testing release (makes this ticket no longer relevant)
