### ISSUE TITLE
Can't recover the right public key on recover

### ISSUE THREAD

**Issue by eduardonunesp** [GetScatter/ScatterDesktop#305]
Need a help to recover the public key which is signed by an user using Scatter, the idea is sign using `scatter.authenticate` and than on backend using `eosjs-ecc` recover the public key. For instance: 

```js
const signature = await state.scatter.authenticate(
        '0123456789ab',
        'ok',
        'EOS5S9Y87EPX6ruKUU5iCCYNAf65e6u8QE5sE9avvubzET4yQ5NPo'
      )
```

then on backend

```js
// SIG_K1_K6sB3T57bPX3PF6LPDXMG3foXhhJQrnTAcr9b6eXQz4DNwhiZ4gDQy8nHMrLKqA4XwZAajzLuvxacGqmZq7DtgDMfM4A6d
const ecc = require('eosjs-ecc')
ecc.recover(signature, 'ok') 
```

But it's returning the wrong pub key, like `EOS7a5pngpCq835AqKBzn1at7Po5QcSt94YPeLrmLbdn7Dng1UFdV`

**Comment by nsjames** [comment]
https://github.com/GetScatter/scatter-js/blob/master/mock-sites/vanilla-eos/index.html#L159

The data is triple hashed and you need to match the hashing.

**Comment by eduardonunesp** [comment]
Thanks @nsjames you're awesome !
