### ISSUE TITLE
Balances not updating. Manjaro KDE

### ISSUE THREAD

**Issue by treepi3** [GetScatter/ScatterDesktop#306]
I've converted some tokens using the built in exchange, as well as made some other transactions using different DApps.

For some reason my balances have not updated and I'm not sure what's wrong. Refreshing them doesn't work. Is there a way to clear the cache or something? I'm using the Linux appimage on Manjaro.

**Comment by nsjames** [comment]
Cleaning tickets for Scatter 11 testing release (makes this ticket no longer relevant)
