### ISSUE TITLE
v10.1.2 Issue Tron account balance not displayed

### ISSUE THREAD

**Issue by rkanadev** [GetScatter/ScatterDesktop#308]
My Tron account balance show 0 TRX but i have funds in that account.
I see my funds correctly on tronscan.org but in Scatter desktop it show 0 TRX
https://tronscan.org/#/address/TYQTaaXhhHzwmm4fdRx5yogFtqomjhgKRz
Is there a way to fix this issue?
![snapcrab_scatter_2019-2-19_17-38-20_no-00](https://user-images.githubusercontent.com/22850009/53052773-9953db00-346d-11e9-9f2f-b5651a01f430.png)

**Comment by nsjames** [comment]
This is actually already fixed for the next release, but that release includes RIDL so it's taking a bit longer. Going to close this for now as it will just become a lingering ticket.
