### ISSUE TITLE
New account active owner keys same even if entered different

### ISSUE THREAD

**Issue by MarkStair** [GetScatter/ScatterDesktop#310]
Hello, noticed an issue with scatter when creating accounts.  If you set different owner and active keys it ignores and makes owner and active same.  I'd be glad to provide more info if you need.

Steps:

1. Got to create account, setup up account name and parent
2. Set different owner and active keys and select create account
3. Account is created with same keys for owner and active such as both from active key.
=>I noticed later that the confirmation is showing same owner/active but didn't notice until after I created the account.

**Comment by nsjames** [comment]
Definitely a bug! Thanks for reporting it. 
I'll add a ticket about it internally as well and close it out when fixed for next update-release.

**Comment by nsjames** [comment]
Fixed for 11
