### ISSUE TITLE
Request: Allow offline signing of transactions

### ISSUE THREAD

**Issue by utilsites** [GetScatter/ScatterDesktop#311]
Request: Allow offline signing of transactions like grey mass voter wallet.
For improved security.

**Comment by nsjames** [comment]
We've gotten this request every now and then and our philosophy about it is pretty much the same every time.

Scatter is **meant** to be used as a hot wallet which connects directly to the internet and other applications. Having offline signing doesn't really make sense within that context. 

For better security a Ledger is always the best choice, even more than offline signing with another machine.

**Comment by utilsites** [comment]
But with a simple change I think scatter could support this, just add a new transaction view: "JSON Raw".
That way user could sign transaction elsewhere.
Although scatter approach makes sense too, many users will not participate in many projects due to security concerns.
