### ISSUE TITLE
Tron sign a string

### ISSUE THREAD

**Issue by winter38** [GetScatter/ScatterDesktop#315]
I am trying sign a string, not transaction. Do Scatter support this one?
In tronWeb it can be done by code - same as sign transaction, but need to give hex data.
```javascript
let hex = tron.toHex('test');
tron.trx.sign(hex);
```
I tried ArbitrarySignature and give a string.
```javascript
const account = scatter.identity.accounts[0];
return scatter.getArbitrarySignature(account.address, 'test', why_we_sign, isHash).then(signature => {
	
			console.log('signature', signature);
});
```
i see window with confirmation, but no any answer after i confirm this. (Uncaught (in promise) TypeError: Cannot read property 'transaction' of undefined) in console of Scatter desktop.

**Comment by nsjames** [comment]
```
let hex = tron.toHex('test');
tron.trx.sign(hex);
```

This likely wont work as it might be trying to tap into the arbitrary signature support for Scatter which is disabled for words over 12 characters.

`why_we_sign, isHash` <-- these parameters are deprecated for now in Desktop. 
However the rest of the method looks fine.

Can you send me a screenshot of the error it is producing?

**Comment by winter38** [comment]
so here is screenshot or error - https://gyazo.com/1400824e2958703c3d5b232a8acbfca7
`Uncaught (in promise) TypeError: Cannot read property 'transaction' of undefined
    at n.<anonymous> (file:///C:/Users/User/AppData/Local/Programs/scatter/resources/app.asar/dist/static/js/app.18a0f05e94d0d3ee941a.js:1:89705)
    at _ (file:///C:/Users/User/AppData/Local/Programs/scatter/resources/app.asar/dist/static/js/vendor.43f90dd0731d3a02f7de.js:24:334019)
    at Generator._invoke (file:///C:/Users/User/AppData/Local/Programs/scatter/resources/app.asar/dist/static/js/vendor.43f90dd0731d3a02f7de.js:24:333807)
    at Generator.t.(anonymous function) [as next] (file:///C:/Users/User/AppData/Local/Programs/scatter/resources/app.asar/dist/static/js/vendor.43f90dd0731d3a02f7de.js:24:334198)
    at n (file:///C:/Users/User/AppData/Local/Programs/scatter/resources/app.asar/dist/static/js/vendor.43f90dd0731d3a02f7de.js:75:278607)
    at file:///C:/Users/User/AppData/Local/Programs/scatter/resources/app.asar/dist/static/js/vendor.43f90dd0731d3a02f7de.js:75:278703
    at <anonymous>`

**Comment by winter38** [comment]
`let hex = tron.toHex('test');
tron.trx.sign(hex);`
I know that hex data to getArbitrarySignature will not work, it is just an examople how i managed to sign a string, not a transaction in tronWeb.js

**Comment by nsjames** [comment]
Okay, yes looks like there is a problem there here: https://github.com/GetScatter/ScatterDesktop/blob/master/src/plugins/defaults/trx.js#L169

I'll have to do some testing and make a switch case for those which allows the arbitrary signatures to work. This will have to wait for an update.

Your alternative immediate solution is signing a real transaction on a contract but not broadcasting it.

**Comment by nsjames** [comment]
This should be fixed now
