### ISSUE TITLE
Misleading "Copy" button

### ISSUE THREAD

**Issue by nicolas-simplex** [GetScatter/ScatterDesktop#316]
There are two different copy buttons on the screen to export keys as text. One of them copies the text that is being shown as expected while the other copies both the public and private key together.
This behavior can easily mislead users to paste a private key when they were trying to paste their public key.
Having two different copy buttons is bad UX anyway.  
![Screenshot from 2019-03-28 16-14-18](https://user-images.githubusercontent.com/751154/55186164-a2268380-5174-11e9-8fb7-0180a8889b7a.png)
(The keys were created for the sake of the screenshot)

**Comment by nsjames** [comment]
Cleaning tickets for Scatter 11 testing release (makes this ticket no longer relevant)
