### ISSUE TITLE
WORBLI addition ends up in EOS Mainnet

### ISSUE THREAD

**Issue by Mariachile** [GetScatter/ScatterDesktop#323]
Hi Nathan,
Have a new WBI set of keys from WORBLI.io and have various tokens in the account. Trying to add it to Scatter. When I click Add Keys, Import an existing key, Import private key as text, and paste the Active Private key in, it imports it and automatically goes to the Key Name screen. At that point I put the name of the WBI account in the top field and click refresh. Nothing seems to be accomplished. Then, 
When I go back to the Key Name page and Add account the only option available seems to be adding EOS.
Since EOS Mainnet was the only network showing, I went into settings and added WORBLI network. After doing that I was able to refresh and see the correct number of WBI tokens in the account.
Went to eostoolkit.io and was only able to see the EOS account; the WBI account was not an option showing on the right. Went back into Scatter, selected the account, refreshed, and could see it again. The main purpose of this was to stake most of the tokens. Tried that with Change Permissions and putting half of most of them into CUP and NET, each. Got the attached error message.
Any thoughts?
![TransactionError](https://user-images.githubusercontent.com/49964011/56700569-05023080-66c9-11e9-8211-ea47f50a3f60.jpg)

**Comment by nsjames** [comment]
Cleaning tickets for Scatter 11 testing release (makes this ticket no longer relevant)
