### ISSUE TITLE
Can't sign a transaction on bancor.network in EOS network

### ISSUE THREAD

**Issue by Gutalean** [GetScatter/ScatterDesktop#324]
When trying to convert a token to the other one via https://www.bancor.network I get this message as in screenshot for a long time, and nothing happens then. 

So far I used nodes.get-scatter.com and eos.greymass.com for domains in network tab of the settings.

I have installed Scatter Desktop Companion 10.2.0 on Manjaro linux. Also I've tried previous stable version and different browsers: Chromium and Firefox. But the problem stays.

![Screenshot from 2019-04-25 10-29-57](https://user-images.githubusercontent.com/8298394/56718139-e2166180-6746-11e9-8b14-a77b4b41c905.png)

**Comment by nsjames** [comment]
Yeah, I've already pinged Bancor about this a few days ago. 
Nothing we can do about it from our side, seems some update to their code broke the way data is encoded before being sent to Scatter.

**Comment by nsjames** [comment]
Closing as it isn't relevant to Scatter Desktop
