### ISSUE TITLE
What's the point of using an identity public key for authentication?

### ISSUE THREAD

**Issue by Jeiwan** [GetScatter/ScatterDesktop#326]
Since this public key is not known to a backend server there's no way to actually verify a signature. Providing the public key alongside the signature makes no sense because it must be obtained from a trusted third party. When an account's public key is used, the backend server can query a real public key from an EOS node and verify the signature against it.

**Comment by nsjames** [comment]
You **make** the public key known to **your** back-end server. 
Think of it like a central-less oAuth login. You store the public key for reference alongside a `uuid` and then re-validate the identity key for each login, proving that the user is someone already registered.

**Comment by Jeiwan** [comment]
Is there any need to prove validity of a public key and/or a uuid when the initial request (registration) is sent to my back-end server? Anyone can send any public keys and that seems to be ok, right?

**Comment by nsjames** [comment]
On the initial request yeah, any key would be fine, same as any email being fine for registration. 
It's the recurring users that the authentication is good for.

**Comment by Jeiwan** [comment]
Got it. Thanks for clarifying.
