### ISSUE TITLE
There is no longer a way to set a display token

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#329]
This was a great feature that I think users will miss. We can use the new popin you developed for send/exchange for selecting the secondary token to show.

![Screen Shot 2019-05-13 at 12 38 34 PM](https://user-images.githubusercontent.com/814302/57611734-29d91d80-757c-11e9-9e7a-2f70787c07ad.png)

**Comment by nsjames** [comment]
58019d928aa013f7aabf90d4cd70f9386bc6af11
