### ISSUE TITLE
We need to work out auto-login for Marketplace and RIDL

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#333]
So I think one of the wonky things that we're encountering now that we are just pulling in the websites for Marketplace and ridl.network is that we expect users to login from within Scatter.

I think we have one decent option here: when the page loads, we need to force the user to choose immediately what user he wants to log in as. For RIDL, we should force the user to create an identity then and there.

I'm open to other suggestions :)

![Screen Shot 2019-05-13 at 12 46 40 PM](https://user-images.githubusercontent.com/814302/57612451-88eb6200-757d-11e9-9e3a-0e5adaad7527.png)

**Comment by nsjames** [comment]
The only way we can currently do this is by breaking best practices and confirming to a "login on opening website" like some of the dapps do, which isn't great UX. 

However, we can enable that functionality only through a query string flag on the sites and default to best practices when reaching the site without it.

**Comment by ramijames** [comment]
> The only way we can currently do this is by breaking best practices and confirming to a "login on opening website" like some of the dapps do, which isn't great UX.
> 
> However, we can enable that functionality only through a query string flag on the sites and default to best practices when reaching the site without it.

Since we control ridl.network, we can send a parameter from Scatter that has special behavior which sends a request to login. I want it to not feel like a website we are loading into Scatter. That means it should:

1. On first load, If there is no account: create one
2. If there is a single account: load that ridl account
3. If there are multiple ridl accounts: ask which account you want to use

For regular web users it wouldn't affect them.

**Comment by ramijames** [comment]
> We should still have a logout functionality though, as users might want to change the account they are using to interact with it.
> 
> For Marketplace it will be using the new `loginAll` which might not require a logout since it will have permissions set up to see all accounts, but in the future once users can filter out accounts they don't want to expose then we'll have to rethink that process.

This wouldn't be logout, it would be "add account" like google does:
![Screen Shot 2019-05-13 at 9 59 01 PM](https://user-images.githubusercontent.com/814302/57646904-59af1200-75ca-11e9-90c8-2b7bc1fc1346.png)

Then the user can switch accounts from a dropdown. 

Really this should be an external component that both RIDL and Marketplace share, since the functionality will be identical.

**Comment by nsjames** [comment]
This can be handled on the dapp. Bloks.io does this.
