### ISSUE TITLE
Contacts in each chain should be verified

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#335]
In each chain, we should be checking that these addresses exist and are valid. It would be awful if someone added a contact that wasn't valid and sent funds that disappeared into the ether.

![Screen Shot 2019-05-13 at 1 02 08 PM](https://user-images.githubusercontent.com/814302/57613373-62c6c180-757f-11e9-9fb7-0e620237689c.png)

**Comment by nsjames** [comment]
This could actually backfire in a few ways.
Network conditions might make it unstable, the fact that it exists on the blockchain doesn't make it valid in the sense that it's the one they mean it to be (false positive), and we'd also need to add UX for specifying which network it should belong to (not blockchain) or adding a check for each enabled network of that blockchain's type.

**Comment by ramijames** [comment]
Sure, but there is definitely local checking that we can do. Accounts should be 12 characters. We know the basic format of ETH addresses, TRON addresses, and Bitcoin addresses (http://mokagio.github.io/tech-journal/2014/11/21/regex-bitcoin.html).

**Comment by nsjames** [comment]
Yes, absolute we can validate them a bit and I think the old contacts panel (and transfer panel) did that too. Leaving this open to remind me to add back in those check.

**Comment by ramijames** [comment]
sababa

**Comment by nsjames** [comment]
12b5baf8a686f8914521b8895b0149b7e7bec879

**Comment by nsjames** [comment]
I left out bitcoin for now as it isn't an internally supported chain. 
Each blockchain we add will automatically be added support for using the `isValidRecipient()` method on the blockchain's plugin.
