### ISSUE TITLE
"Convert" should be "add blockchain to key" for clarity

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#337]
![Screen Shot 2019-05-13 at 1 10 16 PM](https://user-images.githubusercontent.com/814302/57613857-948c5800-7580-11e9-880c-2f6ce4d2a2a4.png)

**Comment by nsjames** [comment]
I think we need a more exact term for this.

Technically, you aren't adding a blockchain to the key, you are re-formatting the private key into a different public key. 

Perhaps something like "Copy key to another blockchain"?

**Comment by ramijames** [comment]
I think we should figure out a clear way to explain this to users. Maybe convert is correct and I'm misunderstanding exactly what this is doing.

**Comment by nsjames** [comment]
Convert would be _technically_ correct, but might get lost without further explanation.
