### ISSUE TITLE
 Why is language only in English?

### ISSUE THREAD

**Issue by goingos** [GetScatter/ScatterDesktop#34]
![_20180819120538](https://user-images.githubusercontent.com/41921163/44305377-3727f980-a3a8-11e8-9848-81e9d2337fb2.png)

**Comment by nsjames** [comment]
Scatter Desktop is still in Open Beta and subject to large UI changes. To make sure translators aren't doing work over and over again no translations have been requested yet. Once the UI is locked down bounties for translations will be given.
