### ISSUE TITLE
Donate RIDL panel

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#340]
![Screen Shot 2019-05-13 at 1 23 55 PM](https://user-images.githubusercontent.com/814302/57614735-9c4cfc00-7582-11e9-85f3-b9353b81ff37.png)

It feels like nothing happens after you donate and click allow. The notification that you've purchased is tiny and placed strangely. I suggest moving it down near the button. After donation the text of the button should be "Donate again"

**Comment by nsjames** [comment]
d03d2ad070b60f945cb63f705483b736ace63b8d
