### ISSUE TITLE
Links to Terms, Privacy Policy, and Support don't work

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#342]
![Screen Shot 2019-05-13 at 1 32 54 PM](https://user-images.githubusercontent.com/814302/57615178-c4892a80-7583-11e9-8a4e-9278c38eda18.png)

**Comment by ramijames** [comment]
Support is: https://support.get-scatter.com/

We still don't have terms + privacy policy up. We should take these links out in the meantime.

**Comment by nsjames** [comment]
150ff7d64f64781cc09e2211fe36ad4ae96f13a7
