### ISSUE TITLE
Creating a new Scatter fails after reset

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#344]
1. Reset Scatter
2. Create new
3. Enter password
4. Death

![Screen Shot 2019-05-13 at 1 40 36 PM](https://user-images.githubusercontent.com/814302/57615729-0ff00880-7585-11e9-9a07-a3dc6eba99df.png)

**Comment by ramijames** [comment]
This managed to perma-fuck my Scatter :(

**Comment by ramijames** [comment]
I still get the "Uncaught (in promise) Error: ENOENT: no such file or directory, mkdir '/Users/mac/Library/Application Support/scatter:/scatter_backups'" error after manually creating the directories in that path

**Comment by nsjames** [comment]
f9acecd58091625303b189b96791be4ce780bcbd
