### ISSUE TITLE
Hash bug with back arrow error

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#345]
1. wallet
2. single account
3. exchange button (top right)
4. back arrow (top left)
5. wtf?

movie of exact process to reproduce is attached.

[bug.mov.zip](https://github.com/GetScatter/ScatterDesktop/files/3174649/bug.mov.zip)

**Comment by nsjames** [comment]
a5e925c6c01b0f5d8146686a6e8745d2ffbf3303
