### ISSUE TITLE
Selecting keys dropdown in "change keys" is not centered

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#346]
The dropdown should also be much wider to show the full key easily.

![Screen Shot 2019-05-14 at 5 22 26 PM](https://user-images.githubusercontent.com/814302/57705700-017d1c00-766d-11e9-9f2f-23ebd2211b19.png)

**Comment by nsjames** [comment]
64b65fe3d09ad329511427f612b8501d6c2bbe30
