### ISSUE TITLE
Resizing Scatter window doesn't update the width of slides in carousel

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#350]
<img width="1197" alt="Screen Shot 2019-05-15 at 5 24 21 PM" src="https://user-images.githubusercontent.com/814302/57783212-6b152d00-7736-11e9-9cc4-c7cf5d8266f5.png">

**Comment by nsjames** [comment]
fd8e023a70948453fb373b993d57599337f85e4e
