### ISSUE TITLE
Allow the ability to hide Token balance

### ISSUE THREAD

**Issue by DenisCarriere** [GetScatter/ScatterDesktop#352]
Having the ability to hide token balances from being displayed would help people sharing their screens when doing a demo of Scatter or even sometimes when signing a transaction with Scatter the Desktop version pops up and shows your token balance.

For privacy concerns, it would be very helpful to have a setting to toggle on/off viewing the token balance in the "home page".

When sending tokens, you need to know your token balance, so these balances wouldn't be hidden.

**Comment by nsjames** [comment]
That's an interesting point indeed.

**Comment by nsjames** [comment]
84bdd406adbc5f1f45d17087f4e4b9abd2ae775e

**Comment by DenisCarriere** [comment]
Woohoo! 🎉  much appreciated @nsjames !
