### ISSUE TITLE
Trying to unstake tokens but getting transaction net usage is too high

### ISSUE THREAD

**Issue by hagginoaks** [GetScatter/ScatterDesktop#355]
Attempting to unstake all my tokens but met with the following error:

`"transaction net usage is too high: 184 > 0"`

How can I get around this? My goal is to unstake and then send the tokens elsewhere.

**Comment by nsjames** [comment]
You don't have enough NET resources. You need to stake NET first.
https://support.get-scatter.com/article/78-staking-and-network-resources

**Comment by danymo1221** [comment]
That wiki doesn't work.
