### ISSUE TITLE
Need a way to pin or collapse/expand the sidebar

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#357]
I know it is all fancy, but after using it for a week, I find the hover sidebar super annoying. There at least needs to be a way to pin it open or have a more traditional collapse/expand. 

My preference is just having it open all the time and having the main window be wider by default.

![Screen Shot 2019-05-18 at 8 59 48 PM](https://user-images.githubusercontent.com/814302/57973341-357b7880-79b0-11e9-83c4-2ac4f1fd9809.png)

**Comment by nsjames** [comment]
f40be663eecb8afdddd559a9fd9f09153a9539c6
