### ISSUE TITLE
Filter tokens with low values

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#360]
I find it super irritating that my assets panel is full to the brim with tokens that have low values, that I either don't have interest in, or that are used as a marketing ploy to get me to use them.

I think we should add a way for users to filter low values. There are two ways we can go about this:

1. We can add this in settings, and just have a value we think should be the minimum to show. Tokens below that value just don't show up in the list, but would be aggregated as "other tokens" so that the total value of the accounts adds up correctly.
2. We can have a toggle that we have a default minimum (say $0.50) that the user can change in settings.

![gs_desktop_assets](https://user-images.githubusercontent.com/814302/57982643-b1c59880-7a50-11e9-9b4c-44ba64fad6cf.png)

**Comment by nsjames** [comment]
So this functionality already exists in the `settings -> tokens -> settings` panel. It just wasn't connected to the assets display. Fixed in the below commit.

9d9d1463c1d32e3ee266af7ab65d9f840664ec05
