### ISSUE TITLE
Revoke access button doesn't work

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#361]
Seems that this button isn't hooked up to any logic. I don't think it should be showing at all for apps that I haven't used before.

<img width="921" alt="Screen Shot 2019-05-19 at 5 19 47 PM" src="https://user-images.githubusercontent.com/814302/57983438-8182f780-7a5a-11e9-86a0-d043c3d42e4f.png">

**Comment by nsjames** [comment]
9d9d1463c1d32e3ee266af7ab65d9f840664ec05
