### ISSUE TITLE
Account selection token total is incorrect

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#362]
When I go to send tokens, the account selection shows incorrect token amount. Where it should show a single selected account's token total, it shows the total tokens of all accounts with that asset.

**Showing one account selected**
![Screen Shot 2019-05-19 at 9 53 57 PM](https://user-images.githubusercontent.com/814302/57986672-a12d1680-7a80-11e9-91f7-a42788079da8.png)

**But here you can see it is actually the total EOS for all accounts**
![Screen Shot 2019-05-19 at 9 54 47 PM](https://user-images.githubusercontent.com/814302/57986687-c4f05c80-7a80-11e9-9af7-d55343ab21df.png)

**Comment by nsjames** [comment]
9d9d1463c1d32e3ee266af7ab65d9f840664ec05
