### ISSUE TITLE
Scatter 11 throws an error instead of focusing to window if you relaunch it when it's running

### ISSUE THREAD

**Issue by BenAlthauser** [GetScatter/ScatterDesktop#364]
If you launch Scatter 11 when it's already running, you get 

Uncaught Exception:
ReferenceError:argv is not defined
    at App.<anonymous>
app.asar\electron.js:130:49 at App.emit (events.js:194:13)

**Comment by nsjames** [comment]
2a33728a93c8af4c91a88423ae2ebb2d58e29c9d
