### ISSUE TITLE
Can't import Ethereum private key exported from Metamask

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#365]
Private key is exported from Metamask.

I get this:

<img width="821" alt="Screen Shot 2019-05-23 at 11 29 52 PM" src="https://user-images.githubusercontent.com/814302/58284158-b1136600-7db2-11e9-9b10-d3242b0d720b.png">

**Comment by nsjames** [comment]
Should be fixed with latest release
