### ISSUE TITLE
Login Popup - Choosing a permission when multiple are imported

### ISSUE THREAD

**Issue by xemuj** [GetScatter/ScatterDesktop#366]
When I have the same key both permissions (active and owner) scatter by default use active and this version (11) don't give me an option

**Comment by nsjames** [comment]
Ah yes. This is something we're discussing internally as well. Not quite sure how to allow logging in with owner yet without 

- A) Exposing the user who might not be informed about the implications of doing so
- B) Making it seamless in the UI

Suggestions on this ticket are welcome of course.

**Comment by nsjames** [comment]
a3053902fd840be9be0aac6ada40c729e4401db9
