### ISSUE TITLE
Keypair Importing & Exporting

### ISSUE THREAD

**Issue by blackwatertepes** [GetScatter/ScatterDesktop#37]
We'd like to have the ability to import & export keypairs from Scatter! @nsjames I'm moving the conversation over here, to keep track of the entire feature status, while making changes to the codebase easier to consume.

I've broken it down into 3 steps, that make sense, from my perspective. First being a simple code refactor, that preps for the feature, and shouldn't require much additional work. The second change being the ability to import keypairs, since it involves less security than exporting, and is more important for us. We want to provide our users with a file they can import into Scatter, and voila! 

Suggested Roadmap:
* [Refactor the BackupService](https://github.com/GetScatter/ScatterDesktop/pull/36)
* [Add the ability to import encrypted keypair files](https://github.com/API-market/ScatterDesktop/pull/2/files)
* [Add the ability to export encrypted keypair files](https://github.com/API-market/ScatterDesktop/tree/feature/export_keypair)
** Should require the user to enter their password, before exporting

Continued from the conversation started from this initial PR: https://github.com/GetScatter/ScatterDesktop/pull/31

**Comment by nsjames** [comment]
Closing as structure has changed significantly and no private key generated outside of Scatter ( on an app ) should ever be imported into Scatter since it's considered tainted.
