### ISSUE TITLE
TRX tokens are not showing up in my account

### ISSUE THREAD

**Issue by thetokendude** [GetScatter/ScatterDesktop#378]
Can someone please shed some light as to why the transfer seems complete, but this balance is not in scatter.

Here is is is tronscan
https://tronscan.org/#/address/TJFvMHNYDMyfz9Jue3QT14axFLRVbsZdQY

**Comment by nsjames** [comment]
duplicate https://github.com/GetScatter/ScatterDesktop/issues/275

**Comment by thetokendude** [comment]
dude, 
help me here. its 2019 06-07
not a duplicate 
having this problem today

**Comment by nsjames** [comment]
Check out my comment here: https://github.com/GetScatter/ScatterDesktop/issues/275#issuecomment-499960787

You can either download the 10.2.0 testing release or the 11.0.0 testing release from this repository which both have fixes for tron balances
