### ISSUE TITLE
TRON TRX VANISHED FROM TRON WIN DESKTOP WALLET

### ISSUE THREAD

**Issue by AKEK114** [GetScatter/ScatterDesktop#383]
I have issue of missing TRX (Approx 25k) from my Windows Tron Wallet. This I came to know once I tried to check in few weeks time yesterday.  My wallet receive address is TDSRex4NF5egmpZdCUhMXjBvt77BGpAvbV

Can anyone help why TRX are not shown or how to recover? I tried few times with TRX customer service and feedback but ALAS they are really not in mood to help apparently .. at least as of now.

**Comment by nsjames** [comment]
There is a TRX bug in the current Scatter (10.1.2). 
Scatter 11 is releasing today which has fixes for it already.

**Comment by nsjames** [comment]
However, this address doesn't show up on tronscan.org

TDSRex4NF5egmpZdCUhMXjBvt77BGpAvbV
