### ISSUE TITLE
Veryfing user identity on server side

### ISSUE THREAD

**Issue by BartolomeoItaliano** [GetScatter/ScatterDesktop#384]
Hi, 
I need to verify user identity on server side, does Scatter provide such an option? Or can I request for it?

Scatter could just provide me with encrypted with private key JSON with user name and date of encryption this way I could easily authorize user with new functionalities.

I will then send this encrypted data to my server and decrypt data on server side with his public posting key from blockchain .

I think providing me with such information would be 100% safe for user and will massively extend Scatter functionality.

**Comment by nsjames** [comment]
You can use `ScatterJS.authenticate()` to get proofs about keys. 

https://get-scatter.com/docs/api-authenticate

**Comment by BartolomeoItaliano** [comment]
Thank you for response!
Do I understand it properly:
"12_CHAR_RANDOM_STRING" I obtain in browser and then in my dapp server I check who is authorized?

**Comment by nsjames** [comment]
You can find some examples here: https://github.com/GetScatter/scatter-js/blob/master/mock-sites/eosjs/index.html#L209
