### ISSUE TITLE
Feature Request: Offline signing a message to import EOS private key

### ISSUE THREAD

**Issue by K2APacific** [GetScatter/ScatterDesktop#386]
I notice several people have either been phished or a key logger virus has captured their private key when they first setup Scatter for EOS. As a feature request, can you add an option where an offline signed EOS message (which proves account ownership) could be imported to access the EOS account the very first time (only needed one time only per account) ? The option for Ledger and Private key import would stay, an offline import would simply be another option which would avoid phishing and key logger scams. As for the Ledger, it is not open source, so I won't use it. Thanks for making a great EOS Wallet !

**Comment by nsjames** [comment]
So really, you can already import a key offline. 
You can simple import that key on an airgapped machine, export a backup from Scatter, and then import the backup on the other computer.
