### ISSUE TITLE
In version 11 It's impossible to add EOS based networks accounts (Telos, Worbli, etc)

### ISSUE THREAD

**Issue by nicolas-simplex** [GetScatter/ScatterDesktop#389]
Given the option to manually add account names to key pairs is gone and given the refresh feature only searches for existing accounts on EOS Mainnet there is no longer a way to import accounts from other EOS networks.

**Comment by nsjames** [comment]
Hold down CTRL when you click on the dropdown menu for the keypair. It will allow you to access the manual `Link Account` option.

However, Scatter doesn't only search for accounts on mainnets. It will search for accounts on any network that has a `history plugin` enabled. Without that, it's simply impossible to know what accounts belong to a key.

**Comment by nicolas-simplex** [comment]
Looking at this code I was under the impression that Scatter was only using https://api.light.xeos.me/api to search for accounts based on a public key. Am I missing something?

https://github.com/GetScatter/ScatterDesktop/blob/master/src/plugins/defaults/eos.js#L33

**Comment by nicolas-simplex** [comment]
Thanks for the info @nsjames, I'm closing this ticket now
