### ISSUE TITLE
Can't transact, blocking shadow layover

### ISSUE THREAD

**Issue by bitcoiners** [GetScatter/ScatterDesktop#390]
After installing latest release 11, I can no longer transact with Scatter. From sending screen when clicking Send button, a blocking grey layover screen comes up.
Running on Ubuntu 18.04.

**Comment by nsjames** [comment]
Turn off PIN from settings.
There's a patch ready to go but waiting for more bugs to close.

**Comment by bitcoiners** [comment]
turning off pin does not help. will wait for patch

**Comment by nsjames** [comment]
If it's not the PIN issue then we're gonna need more information.
Can you open the console (f12) and then check for errors there and post screenshots of them?

**Comment by nsjames** [comment]
ping

**Comment by bitcoiners** [comment]
sorry, been busy, will post update soon.
