### ISSUE TITLE
Missing dev dependency: compression-webpack-plugin

### ISSUE THREAD

**Issue by jcalfee** [GetScatter/ScatterDesktop#392]
```bash
$ npm run build

> scatter@11.0.0 build /home/james/opt/ScatterDesktop
> concurrently "npm run copybuildfiles" "node build/build.js"

[0] 
[0] > scatter@11.0.0 copybuildfiles /home/james/opt/ScatterDesktop
[0] > copyfiles splash.html dist
[0] 
[0] npm run copybuildfiles exited with code 0
[1] internal/modules/cjs/loader.js:605
[1]     throw err;
[1]     ^
[1] 
[1] Error: Cannot find module 'compression-webpack-plugin'

...

$ git branch
* (HEAD detached at 11.0.0)

```

**Comment by nsjames** [comment]
Probably same issue as here: https://github.com/GetScatter/ScatterDesktop/issues/393#issuecomment-505601063

**Comment by jcalfee** [comment]
Yarn worked better.  I did a reset and blew away node_modules.  I still needed `yarn add bufferutil utf-8-validate` before the install would work.  The release-linux worked.  Close if you like or you might use this ticket to add those dependencies.

Wow looks great, once again..  Thank you!

**Comment by nsjames** [comment]
Those dependencies are actually left out on purpose. They serve a part of a third party lib that isn't needed and cause bloat.
