### ISSUE TITLE
Polish: Add Transition animation when updating right hand panels

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#4]
Might be a nice to have little extra spit of polish when updating right hand panels with new entries (e.g. key pairs, networks):

![image](https://user-images.githubusercontent.com/2923/42549652-497379ec-849b-11e8-999e-ae1fdb23812e.png)

**Comment by nsjames** [comment]
Done deal fcdf63c22b73c0988564050961960e4c994a861c
