### ISSUE TITLE
Can't select `http` protocol in network setting

### ISSUE THREAD

**Issue by jacktang** [GetScatter/ScatterDesktop#405]
Hello,

I migrated scatter chrome extension to desktop. But I can't choose `http` protocol in network setting. The version of scatter is `11.0.0` and OS is `macOS mojave 10.14.5`

**Comment by nsjames** [comment]
722c3c0fdbeef270280c553aaf629659374922ef fixed here and staged for next patch release.
Thanks for the ticket
