### ISSUE TITLE
Transaction window stuck on OSX

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#413]
## What the user sees

When trying to do a transaction on the WAX blockchain the transaction window is stuck with dimmed styling for user `@BirchStorey` in Telegram:

![image](https://user-images.githubusercontent.com/2923/60751189-8c003e80-9f7f-11e9-96f4-53d406670266.png)

This is on:

* OSX
* Scatter 11
* Chrome (incognito window)

Apparently the Firewall is enabled in OSX, which I've never seen enabled, so not sure exactly how it works but here's some info from Apple: [Mac OSX Firewall info](https://support.apple.com/en-ca/HT201642)

![image](https://user-images.githubusercontent.com/2923/60751205-cd90e980-9f7f-11e9-862f-0b6c5c3ce3c2.png)

Apparently by default all unsigned applications are disallowed in the Firewall, but not sure how it works, like if it then asks to whitelist certain apps.

Trying to look in Scatter's console window didn't seem to show any errors.

## Background

Supposedly Scatter 10.1.2 worked just fine a few days earlier. My theory is that potentially that app was manually whitelisted in the Firewall at some point, but not the new version of Scatter.

**Comment by nsjames** [comment]
This should be just the PIN bug.
That particular color of opaque background means there's supposed to be a pop-in, and in 11.0.0 it was missing the PIN pop-in component which caused this exact error. He should be able to just go to `Settings -> Password` and disable the PIN to fix the issue. Already applied a patch to master, just waiting to release a new build.

**Comment by nsjames** [comment]
Closing this now as the issue was resolved in 11.0.1
