### ISSUE TITLE
Fonts missing macOS

### ISSUE THREAD

**Issue by kesar** [GetScatter/ScatterDesktop#42]
<img width="529" alt="screen shot 2018-08-27 at 13 48 55" src="https://user-images.githubusercontent.com/1288106/44658155-01b28a00-aa00-11e8-8135-bc5c8e817ab6.png">

**Comment by kesar** [comment]
seems to be most likely from the

 lib:https://github.com/KyleAMathews/typefaces/blob/master/packages/grand-hotel/index.css#L11

not big deal, perhaps worth to open there

**Comment by nsjames** [comment]
Yeah those aren't actually used which is why they are omitted from the package. I should probably fix the annoying error though :P

**Comment by nsjames** [comment]
Fixed in next version ( 9.6 )
