### ISSUE TITLE
Accounts list doesn't stand out

### ISSUE THREAD

**Issue by nsjames** [GetScatter/ScatterDesktop#421]
![image](https://user-images.githubusercontent.com/10360675/61177309-c8184c80-a5da-11e9-8242-d1d6ab64a815.png)

The accounts on the right in the assets panel are hard to see/read.

**Comment by ramijames** [comment]
Already fixed in the latest version:

![Screen Shot 2019-07-14 at 11 55 52 AM](https://user-images.githubusercontent.com/814302/61181367-608bec80-a62e-11e9-9b43-af939047babe.png)
