### ISSUE TITLE
Popup buttons became small

### ISSUE THREAD

**Issue by nsjames** [GetScatter/ScatterDesktop#422]
Now
![image](https://user-images.githubusercontent.com/10360675/61177327-47a61b80-a5db-11e9-9566-ca81122c5bec.png)

Before
![image](https://user-images.githubusercontent.com/10360675/61177333-6b696180-a5db-11e9-8352-2c3ded4647b5.png)

It was much easier to tap those buttons before

**Comment by ramijames** [comment]
I'm trying align button sizes with standard OS patterns and not web patterns. I want Scatter to be more like a native app and less like a web app.

https://docs.microsoft.com/en-us/previous-versions/ms997619(v=msdn.10)

https://ux.stackexchange.com/questions/9997/what-is-the-ideal-height-of-a-button-in-regular-desktop-applications
