### ISSUE TITLE
X on bad password doesn't clear the password field

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#424]
1. Enter bad password
2. Hit X

X tries to log you in again.

<img width="1118" alt="Screen Shot 2019-07-16 at 9 12 47 PM" src="https://user-images.githubusercontent.com/814302/61318802-8ec82280-a80e-11e9-82d2-d8c038b97d21.png">

**Comment by nsjames** [comment]
The "X" doesn't actually exist anymore. It goes right back to chevron.
