### ISSUE TITLE
Search in contacts doesn't work

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#425]
<img width="1092" alt="Screen Shot 2019-07-16 at 9 14 31 PM" src="https://user-images.githubusercontent.com/814302/61318892-c33bde80-a80e-11e9-8b11-41104550bb55.png">

**Comment by nsjames** [comment]
Fixed here: https://github.com/GetScatter/ScatterEmbed/commit/d3ed556dd148c4b78235759fca5856c46904e3d1
