### ISSUE TITLE
Contacts list in Send overflows

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#426]
<img width="1075" alt="Screen Shot 2019-07-16 at 9 16 31 PM" src="https://user-images.githubusercontent.com/814302/61319036-0e55f180-a80f-11e9-9ee0-ee6dca03b6fe.png">

**Comment by nsjames** [comment]
Fixed here: https://github.com/GetScatter/ScatterEmbed/commit/eadd8cbeb75bcaeae39539214cf9cdf1361ae02c
