### ISSUE TITLE
Scatter 11 does cannot link accounts that have given permission to a main account

### ISSUE THREAD

**Issue by RavenXce** [GetScatter/ScatterDesktop#436]
Scatter 11 removed the ability to manually link accounts to keys. However pressing "link accounts" is not able to detect additional accounts that accounts already under that particular key may also have permissions for.

What is the solution for this? At the moment it is impossible to choose the correct key to sign / login to external apps, or even transfer tokens for the delegated account.

**Comment by nsjames** [comment]
You can tap the CTRL button when you click on the "Actions" dropdown from the keypair in Wallet.
That will expose the manual linking behavior. 

We hid the functionality due to a mass amount of tickets from users who linked an account that didn't belong to the key they imported.

**Comment by RavenXce** [comment]
I see, thank you!
