### ISSUE TITLE
No popup anymore when asking for an identity

### ISSUE THREAD

**Issue by raphaelgodro** [GetScatter/ScatterDesktop#44]
Hello!

Scatter Desktop 8.7.0
Scatter-js 2.5.1
My OS is MAC OS X High Sierra 10.13

Yesterday my Scatter Desktop and scatter-js worked fine but today I receive null identities.
I run Scatter Desktop. So basically, my websocket connects fine but ScatterDesktop doesn't pop any window in which I can choose my identity. It sends over a null identity and the getIdentity promise get resolved.

I don't know if the issue is at the Scatter Desktop level or scatter-js, on which side of the websockets there is an issue.

**Comment by raphaelgodro** [comment]
I had to recreate my identity on Scatter Desktop and now the popup appears. Seems to have a link with app linking (with the app name), just a guess though.

**Comment by nsjames** [comment]
Hard to debug without any error messages. I'm going to close this for now. If anyone else gets this issue comment here and I'll reopen it.
