### ISSUE TITLE
Newly imported account doesn't show up when logging into websites

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#440]
## Problem

I had this problem at least twice before, and now another user [reported it in Telegram](https://t.me/Scatter/97781) as well.

I haven't tried to replicate it myself again to confirm, but fairly sure this is a legit issue right now, most likely related to some keypair/account cache in scatter is my guess.

## Replication steps

1. User adds new keypair in scatter OR user adds new account to existing keypair in scatter
2. EOS account shows up fine in Scatter
3. When using a website that supports scatter login the Scatter popup with the account selector does not have that new account

User is unable to log in to the website even though inside of Scatter everything looks fine and that account seems usable within Scatter.

Key/Account imported in Scatter:

![image](https://user-images.githubusercontent.com/2923/62721951-62ea2800-b9db-11e9-8937-b6940bee242b.png)

Key/Account not showing up on e.g. eostitan:

![image](https://user-images.githubusercontent.com/2923/62722037-8d3be580-b9db-11e9-976b-495eaa69a991.png)

**Comment by nsjames** [comment]
Fixed here: https://github.com/GetScatter/ScatterEmbed/commit/1c73e455ec9f714e9a80e273b10f86e62fe8df2c
