### ISSUE TITLE
Mild annoyances of login screen

### ISSUE THREAD

**Issue by GassaFM** [GetScatter/ScatterDesktop#443]
Here is my usual experience of logging into Scatter 11.0.1 (OS Windows).

1. I open Scatter, then another window. Then I see the password input field and click on it to input the password.
![image](https://user-images.githubusercontent.com/2153020/62838185-6c94b980-bc81-11e9-9a55-03354b8f83e2.png)

2. But the rightmost part of the input field is actually an invisible button! So, instead of waiting for the password, Scatter thinks a bit and says the (empty) password is bad.
![image](https://user-images.githubusercontent.com/2153020/62838190-74ecf480-bc81-11e9-87bc-16f71c1015d9.png)

3. After unsuccessful password input, the cursor is no longer in the input field, and I have to move the mouse into the input field again, click there, and only then input the password.

So, the expected process is: click safely in the Scatter window, type the password, press Enter, type it again if unsuccessful. Empty password does not trigger password check.
The actual mild hindrances are: click specifically in the input field and not in the rightmost part of it, and then make additional moves (click there again or press Tab) if unsuccessful. Empty password triggers password check.

**Comment by nsjames** [comment]
https://github.com/GetScatter/ScatterEmbed/commit/c197dffa01d1b654ddc8b92451fd0ffeaf4db36a fix for #1 and #2

https://github.com/GetScatter/ScatterEmbed/commit/ddfd7ce3ea18a7faec706b485c8872a1098e0892 for #3
