### ISSUE TITLE
Support Sending/Exchange of WAX tokens

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#444]
Right now users are complaining that they can only see the balance of tokens, but can't actually use them for anything.

**Comment by greenballon0507** [comment]
I got the same problem. Now it looks like WAX hold our asset for their own benefit. I can not move it to any exchange.

**Comment by nsjames** [comment]
If users can or can't use those tokens for anything that's really out of our control. 
It's up to the WAX team to provide use-cases for their tokens and get them on exchanges that we support internally (like Bancor).
