### ISSUE TITLE
Password strength is annoying

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#446]
Please, let's drop the ridiculous password strength requirements.

**Comment by Soleone** [comment]
👍awesome! see also https://github.com/GetScatter/ScatterDesktop/issues/401

**Comment by nsjames** [comment]
Password requirements have dropped a little, but are still enforcing strong passwords. 

https://github.com/GetScatter/walletpack/blob/master/packages/core/lib/services/secure/PasswordService.js#L19

```
if(!this.isLongEnough(password)) return 'Your password is not long enough (8 characters)';
if(this.uppercaseCount(password) < 2) return `Passwords must have at least two uppercase letters`;
if(this.lowercaseCount(password) < 2) return `Passwords must have at least two lowercase letters`;
if(this.specialCharCount(password) < 2) return `Passwords must have at least two special characters (like # or @)`;
```
