### ISSUE TITLE
"optional"  fields instead of "required"

### ISSUE THREAD

**Issue by filipniziol** [GetScatter/ScatterDesktop#45]
It would work much better because now it returns error if some field is missing. It would be nicer to make a request and get all available fields and null if missing.

**Comment by nsjames** [comment]
This is a fantastic idea.

I think I'll take it one step deeper too. One of the next updating will change the scatter options object to: 

```
{
    requiredFields:[],
    optionalFields:[],
    booleanFields:{
        'personal.name':'Mike', // Is he mike?
        'location.country.code':'US' // Is mike in the USA?
    }
}
```

**Comment by nsjames** [comment]
Fields return null values now when not pre-populated
