### ISSUE TITLE
Sending EOS does not work

### ISSUE THREAD

**Issue by jcalfee** [GetScatter/ScatterDesktop#450]
I click on the send button, the background gets darker out but nothing happens even after 5 min or so.  There are no log messages in the console after clicking the Send button.

![image](https://user-images.githubusercontent.com/204121/63711556-4898b280-c801-11e9-9762-de5218dd5509.png)

Environment:
linux-scatter-11.0.1-x86_64.AppImage
Debian GNU/Linux 9 (stretch)
Use Pin is OFF (turning this on did not change the apps behavior)

Happens in both 11.0.0 and 11.0.1

Other errors on startup:
![image](https://user-images.githubusercontent.com/204121/63711857-f7d58980-c801-11e9-8f74-75e2fddb2f6d.png)

**Comment by ramijames** [comment]
Can you show me your network settings in a screenshot?

**Comment by jcalfee** [comment]
I was thinking, maybe it is something in electronjs.  I used v10 to do what I needed.  I'll test new versions when they are available.

**Comment by jcalfee** [comment]
Probably related to the AppImage .. I'm running Scatter from electron and this issue does not appear.

 https://github.com/GetScatter/ScatterDesktop/issues/457
