### ISSUE TITLE
Issues with starting Scatter

### ISSUE THREAD

**Issue by vox78** [GetScatter/ScatterDesktop#453]
Have an issue to start Scatter from the very beginning. It takes from 3 till 17 times. Average 6-7 times. After pressing Scatter icon on desctop it starts loading and stops.Thought it may be the fault of low specs of laptop or computer settings to blame. Using Adblock Plus too. Just recently used Sqrl wallet to stake Tlos tokens and didnt have issues to start wallet. After each click of wallet icon, even if it takes longer sometimes, wallet screen is being opened.
The issue is so annoying that i start using blockchain dapps much less. Would like to see it fixed because i am a fan of Scatter and a bit invested in Ridl.
Browser Google Chrome, Windows 8.1.
I believe this issue could be important for more users just most of them will not be creating account on Github in order to register the issue, because Scatter support team is not helpfull and ask you to do it yourself.

**Comment by educatedwarrior** [comment]
I'm having the same issue.   I'm using Linux Mint 19.2.   The screen just freezes at scatter startup and I have to reboot the computer.

**Comment by nsjames** [comment]
A new version of Scatter will be coming out soon which completely removes almost everything from the desktop app. This should no longer be an issue once that version comes out so I am closing this for now. If this problem persists past version 11.1.0 then please re-open.
