### ISSUE TITLE
Feature Request: Steem Blockchain (What needs to be done?) 

### ISSUE THREAD

**Issue by ackza** [GetScatter/ScatterDesktop#454]
I know adding another blockchain is a large request but I have access to people with funds and developers to do the necessary ground work within scatter to allow us to enable the steem blockchain and all of its subtokens into scatter, so that we can use it to sign transactions similar to how  steem users currently use Steemkeychain by @mattyice

https://github.com/MattyIce/steem-keychain

This extension is great but I would love to use steem over scatter

Please help me find exactly what needs to be added to begin process of adding another blockchain to scatter, STEEM.. and its Steem-Engine tokens and upcoming SMTs when they come out. I want to position steem to beready to even one day be used on newdex or create its own DEX that can use scatter.

I know this is no easy task but I can get the resources and developers to come check this project out and I will make a persuasive case for them to lay the necessary ground work and foundation to then add STEEM to Scatter.  

SInce https://stateofthedapps.com/rankings shows STEEM as a leading dapp chain, with sometimes half the top 20 or more being steem based dapps, I believe its time steem got some representation with more professional tools like scatter.  We are also in the top 5 a few spaces below EOS on https;//blocktivity.info

I will do what needs to be done to take the proper steps to start adding steem to this open source project but would love any help. Ill be over here on steem engine discord if anyone wants to talk to aggroed or steem-engine staff discord.gg/HQs6u23 it is the Steem-Engine main discord and I would love to even help make a donation to Scatter for making such a great product that i use everyday.

Thank you and may the Holy Larimer Bless you all.

**Comment by nsjames** [comment]
Please move this ticket to: https://github.com/GetScatter/walletpack

You can see in the `packages` directory there a list of supported blockchains.
We will be creating scaffolds for new blockchain plugins as well as a README tutorial for getting started once that project stabilizes.
