### ISSUE TITLE
"Something happened while trying to parse the transaction internally."

### ISSUE THREAD

**Issue by libraonepiece** [GetScatter/ScatterDesktop#458]
transfer:"Something happened while trying to parse the transaction internally." 

scatter console log 
![image](https://user-images.githubusercontent.com/51996597/65377214-c4d8c580-dcdb-11e9-8c52-c723eabe594e.png)

**Comment by libraonepiece** [comment]
EOSTestnet chainID:e70aaab8997e1dfce58fbfac80cbbb8fecec7b99cf982a9444273cbc64c41473 
http://jungle2.cryptolions.io

**Comment by nsjames** [comment]
Most likely this is due to an old eosjs version on the front-end.
