### ISSUE TITLE
Scatter Wallet Restore Error

### ISSUE THREAD

**Issue by djappache** [GetScatter/ScatterDesktop#464]
I have an issue with restoring Scatter wallet from Scatter wallet backup. I'm unable to locate the private key for wax hence the reason I'm trying to restore.

Upon restoring and entering password the message shows "Error Parsing Backup File"

I'm wondering if the reason could be due to using restore on new Scatter Wallet version and the backup was in July 2019, if so anywhere I can obtain older version.

Can anyone help please?

**Comment by nsjames** [comment]
You can get an older version here: https://github.com/GetScatter/ScatterDesktop/releases

However, that error usually signifies a bad password

**Comment by djappache** [comment]
> You can get an older version here: https://github.com/GetScatter/ScatterDesktop/releases
> 
> However, that error usually signifies a bad password

thanks for response.

I'm using same password and have restored from latest backup on new machine without any issues.

**Comment by GuillermoCasanova** [comment]
@djappache what version did you end up installing?

**Comment by djappache** [comment]
Installed older and latest but couldn't retrieve my account, even with backup.

Currently installed Scatter Desktop v11.0.1



Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by GuillermoCasanova** [comment]
@djappache I ended up getting it to work with version 11.0.0 -- had a similar problem as you where I had a backup from 2019 and it wasn't decrypting using phrase/password and backup file. Maybe try 11.0.0 ?

**Comment by djappache** [comment]
I'm sure I tried the version too, will try again.

Much appreciated!

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by djappache** [comment]
hi mate, tried and getting same error parsing backup file.

basically, I'm not able to find private key so lost it all.

Thanks for your help though

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
