### ISSUE TITLE
RIDL Identity

### ISSUE THREAD

**Issue by herrandersen** [GetScatter/ScatterDesktop#469]
Hi Rami & Nathan,
I remember that I bought a RIDL Identity (for 1 EOS) before main net launched.
Now when I tried to set up RIDL in Scatter 12 it tells me to register that name again for 1 EOS. Why is that?

**Comment by nsjames** [comment]
Check out this video for more information about upcoming RIDL changes: https://youtu.be/M2CJ9gKYKXw?t=631
