### ISSUE TITLE
Many TypeError: Cannot read property 'cpu_weight' of null errors

### ISSUE THREAD

**Issue by liamcurry** [GetScatter/ScatterDesktop#49]
I'm seeing these errors in the console whenever I switch to the 'Accounts' tab or click 'Fetch Accounts':

![image](https://user-images.githubusercontent.com/77758/45005781-52f3e800-afc3-11e8-9db7-5cc2a785c56c.png)

**Comment by nsjames** [comment]
This happens when interacting with an old nodeos version that doesn't have that.
I added a check for it before trying to use that object which will be in the next version.
