### ISSUE TITLE
scatter can not connect EOS Testnet

### ISSUE THREAD

**Issue by microfisher** [GetScatter/ScatterDesktop#493]
i don't know waht happend threre, and i'm sure everything is correct:

![image](https://user-images.githubusercontent.com/6093582/78419681-b2701900-767a-11ea-8b8c-bb3a60a47cba.png)

![image](https://user-images.githubusercontent.com/6093582/78419684-bbf98100-767a-11ea-9fe3-eebd821b76ca.png)

**Comment by gtolarc** [comment]
I am having the same problem. @ramijames

**Comment by gtolarc** [comment]
Hmm.. it was solved by completely deleting and reinstalling the scatter. Perhaps the existing settings of users who have upgraded from the previous version interfere with the operation in the new version, so it is good to find the cause.

**Comment by microfisher** [comment]
> Hmm.. it was solved by completely deleting and reinstalling the scatter. Perhaps the existing settings of users who have upgraded from the previous version interfere with the operation in the new version, so it is good to find the cause.

thanks!
