### ISSUE TITLE
Too cumbersome to switch accounts in Scatter 12.1

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#497]
## Problem

For users with multiple EOS accounts it is currently not very intuitive or convenient to switch accounts when e.g. trying to login to bloks.io with two separate accounts one after another.

Right now it is a 4 step process:

1. Settings
2. Accounts
3. Edit Accounts
4. Select new "current" account

It highly depends on the use cases of people on how often they need to switch between accounts.

## Suggestion

Make it easier to discover and more convenient to switch the "current" account.

For example:

1. At the top of every Scatter window next to the balance display the current account name and a switch current account button that brings up a dropdown.

It looks like a problem might be that technically there isn't even only one account "current" at the same time, its many, 1 per blockchain. So really you have 1x EOS, 1x Wax, 1x Telos all "current" at the same time. Making that quick dropdown option at the top a bit more complex.

2. At the very least pull the change account button higher to the top to make it easier to discover.

![image](https://user-images.githubusercontent.com/2923/80152408-9da3e880-8589-11ea-90d5-2aada49f8bc7.png)

I will try to keep adding more user feedback and potential use cases as they come up in chat.

**Comment by Soleone** [comment]
![image](https://user-images.githubusercontent.com/2923/80152294-66cdd280-8589-11ea-9104-654aa5227e0e.png)

![image](https://user-images.githubusercontent.com/2923/80152186-3be37e80-8589-11ea-91af-f5b228dba993.png)

![image](https://user-images.githubusercontent.com/2923/80152224-4d2c8b00-8589-11ea-912e-c83d3fc3feb9.png)

![image](https://user-images.githubusercontent.com/2923/80323050-f5935700-87f6-11ea-8f2e-855f02b6375c.png)

![image](https://user-images.githubusercontent.com/2923/80323422-486e0e00-87f9-11ea-9e5e-6a4a144f2451.png)

**Comment by Soleone** [comment]
The issue of wanting to see your "current" (blue button) account seems also related and might be solved in addressing this issue here:

![image](https://user-images.githubusercontent.com/2923/80152478-b9a78a00-8589-11ea-884e-d1c48fd1e1e9.png)

**Comment by Soleone** [comment]
One idea was to still let dapps like bloks.io submit a known account name to Scatter and have that switch to the new account automatically (maybe with user confirmation):

![image](https://user-images.githubusercontent.com/2923/80322413-dc88a700-87f2-11ea-8838-9f307ea1900d.png)

![image](https://user-images.githubusercontent.com/2923/80323333-b9f98c80-87f8-11ea-99b3-376481479d6b.png)

![image](https://user-images.githubusercontent.com/2923/80556023-3084be80-89a0-11ea-9184-06468e28f69a.png)

![image](https://user-images.githubusercontent.com/2923/80556028-37133600-89a0-11ea-86fb-56fcaf6dc6b1.png)

**Comment by Soleone** [comment]
![image](https://user-images.githubusercontent.com/2923/80323037-e6aca480-87f6-11ea-8437-38df816d0aef.png)

**Comment by Platinumwrist** [comment]
I’m having several issues one is scatter is sending me email so I can create an Eos account with credit card but it’s not allowing me to enter the code to proceed with email code

**Comment by Soleone** [comment]
@Platinumwrist This is a different issue and offtopic here, but let me help you still: You can work around this bug by pressing Tab and then click the textfield again, then it should work to enter the text.

**Comment by Soleone** [comment]
I would consider this fixed in Simple UI 1.0.11. 👍 

At the very least any new problems need a new description and context.
