### ISSUE TITLE
Pressing Help --> Generating Keypairs --> Generate New Keypair has seemingly no effect

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#5]
Because the page is scrolled down all the way a user can't see the result of the new key pair that is showing up above the fold.

![image](https://user-images.githubusercontent.com/2923/42549698-8e75644c-849b-11e8-9873-4e2aaef256ab.png)

**Comment by nsjames** [comment]
I made it scroll up to the previous section when generating a new keypair, and it also pushes a snackbar alert now saying "New keypair generated" on both the wizard and the keypairs panel.
