### ISSUE TITLE
FIO: Request status not updating when status has changed or when new request present

### ISSUE THREAD

**Issue by ericbutz** [GetScatter/ScatterDesktop#508]
Request status: not updating when status has changed or when new request present.

First, if you receive tokens in response to a request:
* Send a request for FIO from Scatter to another wallet.
* Respond to the request and pay the FIO•  FIO balance updates in Scatter
* Go into Show Requests and the status in the Sent screen for the request still shows as sent.
* It should be changed to “Received”

Second, if you send a request from another wallet:
* Open scatter wallet
* Send a request for FIO from another wallet to Scatter
* Wait for transaction to hit blockchain
* Open Show Requests, nothing in Received
* Happens even if you Refresh Balances

**Comment by nsjames** [comment]
This should be fixed in the latest version

**Comment by ericbutz** [comment]
The second issue looks good. Thanks for the fix!
I do not see any items in the Sent Requests so am not able to test the first issue.
