### ISSUE TITLE
Can't enter text in textboxes when trying to setup new EOS account

### ISSUE THREAD

**Issue by MyFleetingDream** [GetScatter/ScatterDesktop#512]
If you're a new user trying to setup an EOS account, it either asks you to enter an email address to setup a Moonpay account or asks you to enter the verification code (if you already entered an email account). However, in both cases, the textbox does not accept text. This issue makes the wallet a non-starter for a new user trying to get into EOS

**Comment by Tacumi** [comment]
I have a same problem.
It can be seen on latest windows 10 and macOS Catalina.

**Comment by nsjames** [comment]
This is actually a hard one to fix internally, since the UI is already an embed. The next version forwards the user to an external moonpay using their browser instead of trying to embed it inside of the embed.
