### ISSUE TITLE
Restoring Scatter with Words

### ISSUE THREAD

**Issue by youngfong13** [GetScatter/ScatterDesktop#514]
I am on OS X with scatter desktop 12.1.1, I'm trying to restore from the words and scatter just keeps showing a spinning wheel. How long should it take to restore?

![image](https://user-images.githubusercontent.com/66805122/84445331-bc317200-ac11-11ea-86b8-d1783a5960d6.png)

**Comment by denknl** [comment]
I'm using 12.1.1 on Windows and experience the same issue. Also tried elevated mode but that won't work either. Tried restore by words and by using keychain, without any success.

In [this](https://github.com/GetScatter/ScatterDesktop/issues/505) issue, someone explains that's due to 'old' keychain or recovery words.

**Comment by teomcam** [comment]
I started searching for an alternative wallet. I can't even access my accounts after installing the last update something called simple IU.

**Comment by aaronmboyd** [comment]
Experienced same issue, mnemonic words from about two years ago, haven't used or re-installed Scatter in that time, probably many major versions behind. Do I need to download a previous version and export a backup file?

**Comment by nsjames** [comment]
There's two concepts of mnemonic phrases in Scatter.
- Before version 12 there was a **password backup** which was 12 words. **These don't regenerate keys.** You need your backup file, or your private keys.
- After version 12 there's the 24 word mnemonic which **does** regenerate keys.

If you have a mnemonic (set of words) that is 12 words only, then it is only a password backup for unlocking your `backup json` files. You will still need the backup files, or the private keys.

**Comment by aaronmboyd** [comment]
@nsjames Fair to close because of the mnemonic misunderstanding, however the infinite spinning GIF could maybe have a UI upgrade to say that something has gone wrong?
