### ISSUE TITLE
Parent/Child Accounts

### ISSUE THREAD

**Issue by StarryJapanNight** [GetScatter/ScatterDesktop#52]
It is possible to assign active/owner permissions of an account to another account (not a key). It would be great if Scatter could support these kinds of account permissions.

**Comment by nsjames** [comment]
This is something I'm looking into, but right now there's no clear way to fetch accounts with parent/child accounts from the chain itself. Might have to defer that logic to block explorers or something. 

TLDR; looking into it!

**Comment by nsjames** [comment]
Scatter 10 should now support this.
