### ISSUE TITLE
Urgent: Can no longer import from hardware

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#524]
When trying to import a keypair from Ledger using the Import from hardware button it no longer works. On the user side just nothing happens. In the console you can see the following null error:

![image](https://user-images.githubusercontent.com/2923/89742233-15791e80-da66-11ea-9bac-6ce9871ec6a2.png)

People with Ledger can no longer use Scatter right now so I would make this a top priority. Probably an easy fix I would assume from the error message.

**Comment by Soleone** [comment]
Also reported on the EOS Reddit: https://www.reddit.com/r/eos/comments/i6rbeq/ledger_integration_broken_on_scatter_1211/

**Comment by nsjames** [comment]
Also fixed here: https://github.com/GetScatter/Bridge/pull/52/commits/0d64608a5b8be04e09145bc1e1228d5bf42b7867

**Comment by mikespax** [comment]
I can't import ethereum key from mac or windows at the moment
