### ISSUE TITLE
Can no longer export public keys

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#525]
When going to the Keys section and on any keypair pressing the Copy public key button nothing happens for the user. In the debug console you can see the following error:

![image](https://user-images.githubusercontent.com/2923/89743405-ed42ed00-da70-11ea-8491-6164f48f879f.png)

Might be related to https://github.com/GetScatter/ScatterDesktop/issues/524

Semi-urgent because it erodes user trust.

**Comment by nsjames** [comment]
Fixed here: https://github.com/GetScatter/Bridge/pull/52/commits/0d64608a5b8be04e09145bc1e1228d5bf42b7867

**Comment by nsjames** [comment]
Fixed here: https://github.com/GetScatter/Bridge/pull/52/commits/0d64608a5b8be04e09145bc1e1228d5bf42b7867
