### ISSUE TITLE
Can not transfer ETH token transfer

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#526]
When trying to send ETH from Scatter 12.1.1 nothing happens for the user, it doesn't work. In the debug console you can see the following error message:

![image](https://user-images.githubusercontent.com/2923/89743786-70197700-da74-11ea-8f9b-4e625a5101f5.png)

Reported by one user [in Telegram](https://t.me/Scatter/125264):

![image](https://user-images.githubusercontent.com/2923/89743792-80c9ed00-da74-11ea-9650-a70bbb749e6a.png)

![image](https://user-images.githubusercontent.com/2923/89743803-98a17100-da74-11ea-98a0-fb24d083dfa7.png)

**Comment by nsjames** [comment]
Thanks, fixed here: https://github.com/GetScatter/Bridge/pull/52/commits/0d64608a5b8be04e09145bc1e1228d5bf42b7867
