### ISSUE TITLE
Issue with whitelisted actions

### ISSUE THREAD

**Issue by nsjames** [GetScatter/ScatterDesktop#57]
Looks like the whitelist that is now segregated into individual actions isn't clearing permissions when all actions are whitelisted causing the user to still have to accept/deny prompts.

**Comment by nsjames** [comment]
This turned out to be a non-issue. The permissions system is working properly but is disabled for dapps with old version of `scatter-js` that don't include the origin authentication system as it would possibly be an attack vector. 

Working as it should.

**Comment by leochan007** [comment]
still have this problem with latest scatter-js 
    "scatterjs-core": "^2.5.0",
    "scatterjs-plugin-eosjs": "^1.4.0",   so the eosjs version is 16.09

if with scatterjs-plugin-eosjs2  eosjs version is 20.x

**Comment by nsjames** [comment]
@leochan007 please open a new ticket with the specifics of your issue along with any error logs you can provide.
