### ISSUE TITLE
Minimize icon for Mac

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#59]
On a Mac the tray is at the top, not the bottom like on windows. So the button icon to minimize could be confusing:

![image](https://user-images.githubusercontent.com/2923/45521791-9b629100-b78d-11e8-9fd9-a333100fc6fc.png)

Maybe another more os-agnostic icon can be used to represent the minimize to tray action, e.g.:

![image](https://user-images.githubusercontent.com/2923/45521740-4f175100-b78d-11e8-8fbc-4c7d6f8d19d6.png)

**Comment by nsjames** [comment]
Heh yeah, who put that dock there :)

I think maybe it's time to add non-font-awesome icons in there.
Right now we're using https://fontawesome.com/v4.7.0/cheatsheet/ which is an older version and doesn't have the best icons.
