### ISSUE TITLE
Noob alert: Potentially confusing top right corner buttons

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#6]
![image](https://user-images.githubusercontent.com/2923/42549750-d21887ec-849b-11e8-889b-26260b5c973d.png)

The Identity textfields in the Help section initially confused me a bit. I already created an Identity and wasn't sure if this was supposed to show the details of that or create a new identity. Then I scrolled down to look for a Save button and didn't find one.

Only a bit later did I finally notice the checkmark in the top right. If the pattern is used consistently throughout the app from the beginning it might be easier to get used to, if used only sometimes then some users like me might not get it right away.

**Comment by nsjames** [comment]
I removed the checkmark and replaced it with a button at the end of the flow along with a menu item explaining that Identities auto-save.
