### ISSUE TITLE
Missing testnet transaction history

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#64]
A user on Telegram noticed the following:

> Playing with the Chintai beta on jungle testnet and it interacted with my jungle identity via Scatter Desktop here OK, but I don't see any history for it in Scatter itself.

I assume right now any non-mainnet transactions are purposely filtered out to display inside of Scatter?

**Comment by nsjames** [comment]
Not purposely but they might be missing required pieces of that infrastructure like the history plugin. 
I've noticed locally that it doesn't work either. Might just be a small discrepancy between versions and some missing field.

**Comment by nsjames** [comment]
Scatter 9 no longer has histories.
