### ISSUE TITLE
Error on Windows after rebuild

### ISSUE THREAD

**Issue by dacom-dark-sun** [GetScatter/ScatterDesktop#66]
Not possible to launch on windows after build and pack with error: 
![image](https://user-images.githubusercontent.com/22520798/45695912-000a5b00-bb95-11e8-8364-98097b4bb7b1.png)

What the right way to figure it out? Compiled on MacOs.

**Comment by nsjames** [comment]
You're building on macos for windows and launching on windows? I don't think that will work now that ledger is supported as it uses some prebuilt libraries for the architecture of the system.

**Comment by dacom-dark-sun** [comment]
So, it should be builded on windows?

**Comment by nsjames** [comment]
Yeah I think 8.9.0+ requires that now since it's using nodejs modules which are prebuilt for architecture specific things like `usb`.
