### ISSUE TITLE
Install ScatterDesktop on Ubuntu 17.10

### ISSUE THREAD

**Issue by bachvtuan** [GetScatter/ScatterDesktop#69]
![screenshot from 2018-09-20 17-57-22](https://user-images.githubusercontent.com/2065400/45814097-bf2e5580-bcfe-11e8-861a-b1ae199d9b7e.png)
I am unable to install, Please see above screenshot.

**Comment by shalomz** [comment]
I got the same error as well, so I just had to download the source code, installed the dependencies and run it. You may find issues installing `usb`, so ensure you have installed `build-essential` and  `libudev-dev`. Just run `sudo apt-get install build-essential libudev-dev` (On Mint/Ubuntu/Debian) before you npm install the dependencies.

**Comment by nsjames** [comment]
Please see this ticket https://github.com/GetScatter/ScatterDesktop/issues/61
