### ISSUE TITLE
Noob alert: Potential Scatter Identity public key confusion

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#7]
Scatter Identity public key that was autogenerated and shows up by default right away could make new users think this is their EOS account key (e.g. "owner" or "active"). Maybe consider making it less prominent in some way or hide behind a click.

![image](https://user-images.githubusercontent.com/2923/42549808-210c7f52-849c-11e8-903b-14aafd55fe4e.png)

**Comment by nsjames** [comment]
Hidden behind button that says "Show Identity Key"
