### ISSUE TITLE
Backup exported from Chrome can't be imported into Desktop

### ISSUE THREAD

**Issue by comfyowl** [GetScatter/ScatterDesktop#71]
Basically I've exported Scatter by using the Backup feature from the Chrome plugin.
Then when I try to import backup with Scatter Desktop it just gives me a parsing error.
is this how exporting-importing is supposed to work? 
Is there compatibility between Scatter Desktop and Chrome?
Thanks.

**Comment by nsjames** [comment]
Yes classic and desktop are incompatible. The structure of the data object is vastly different and some of the encryption mechanisms have changed which make the classic backup undecryptable.
