### ISSUE TITLE
Is it possible to import a mainnet EOS account?

### ISSUE THREAD

**Issue by comfyowl** [GetScatter/ScatterDesktop#75]
I didn't figure out a way to import the EOS mainnet primary key.
Also will it have advanced features for power users like voting etc.?
Thanks and keep up the great work.

**Comment by nsjames** [comment]
I wont have voting but it will have unstake/refund. It already has stake but it happens automatically when you are about to run out of resources.

For importing your account just click the vault button ( top right ), then click the "Add New Secret" button top left in your vault. Put your private key in and it will do the rest for you automatically.

**Comment by comfyowl** [comment]
Great, thanks for the fast reply.
