### ISSUE TITLE
Desktop Version: Where the hell is the private key?

### ISSUE THREAD

**Issue by jaderayub** [GetScatter/ScatterDesktop#77]
Where is the private key? I generated 2 keys, one for active one for owner. Both of them came only with pub key and an eth key. so where can i see the private key?????? jaderayub@yahoo.com.br

**Comment by nsjames** [comment]
Next version will allow exporting in key format. Right now only QR is supported.
df799f78a70583568d9f1b9579f8e630b957c3ac

**Comment by jaderayub** [comment]
and how am i gonna put this qr into my wallet? how can i read it? any app in google store you recomend?

**Comment by nsjames** [comment]
Scatter Mobile can read them, and so can this desktop app. 
If you print it out you can later scan it back into the desktop app or a mobile device.
