### ISSUE TITLE
Noob alert: "23 connected apps" on MyFirstIdentity?

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#8]
Is this still dummy data for development or why do I have 23 apps connected already?

![image](https://user-images.githubusercontent.com/2923/42550024-2aa81e26-849d-11e8-9009-860b3a066064.png)

**Comment by nsjames** [comment]
Whoops, yup hidden for now.

**Comment by nsjames** [comment]
Actually, just added the amount of identity only permissions there instead.
