### ISSUE TITLE
9.0.0 doesn't work where 8.9.0 did

### ISSUE THREAD

**Issue by GassaFM** [GetScatter/ScatterDesktop#82]
I'm having trouble with Scatter Desktop 9.0.0 where 8.9.0 is fine.

One such place is [newdex.io](https://newdex.io): when you revoke a deal, the old behavior is a popup with "arbitrary signature", but the new Scatter Desktop just pops nothing.

The second example is [eostoolkit.io/multisig/sign](https://eostoolkit.io/multisig/sign): again, when I press the "Sign" button, the old Scatter pops up a prompt with some numbers, and the new one just does nothing.

**Comment by GassaFM** [comment]
Did the new version just disable signing arbitrary transactions? Because both examples are classified like that.

**Comment by nsjames** [comment]
Yup looks like there was two errors there, one relating to the big change in keypair structure and one related to the resource checks which made it get stuck when popping up and/or clicking accept. I went ahead and fixed them for the next release.
