### ISSUE TITLE
Scatter Desktop displays empty window on Win10

### ISSUE THREAD

**Issue by PiranhaUK** [GetScatter/ScatterDesktop#85]
I just installed the latest version (previously had v8.9.0 installed) and after importing my backup and entering my password the window just clears and displays a white empty window. 

I'm running on the latest version of Windows 10.

**Comment by adsactly** [comment]
Same here going back to previous version that worked perfectly fine.

**Comment by nsjames** [comment]
Fixed for next release

**Comment by cppfuns** [comment]
> Fixed for next release
Has the fixed code been submitted? I want to merge into my own branch

**Comment by nsjames** [comment]
Yup should be
