### ISSUE TITLE
Multiple account support

### ISSUE THREAD

**Issue by jjssoftware** [GetScatter/ScatterDesktop#86]
At the moment it is possible to add keys for multiple mainnet accounts and those accounts be recognized successfully. Once that is done it doesn't appear to be possible to send tokens between those accounts solely within scatter. In the transfer view customize section it would appear that only one of my mainnet accounts (my primary account) is shown in the 'From Account' dropdown.

Being a wallet type app might not be a primary goal of scatter. Is this a bug or a future planned feature? Or perhaps I've just done something wrong.

**Comment by nsjames** [comment]
If you click the little "eye icon" then it will show all accounts.
It's parsing the accounts that have sendable tokens right now, which sometimes is a little buggy since it's pulling that data right off the chain.
