### ISSUE TITLE
Signing with private key in the vault not working when also using hardware wallet

### ISSUE THREAD

**Issue by amani1104** [GetScatter/ScatterDesktop#88]
When two accounts are used in Scatter, where one is secured by a hardware wallet (Ledger Nano S) and the other one stores the private key in the vault, signing transactions with the private key in the vault does not work. In such a case, Scatter always asks to confirm the transaction with the hardware wallet, although the private key is not stored in the device, and thus the transaction cannot be executed and fails.

**Comment by gerakis** [comment]
I am not having this problem. I also have both hardware and non-hardware wallets in my scatter. Try making sure that the non-hardware wallet is selected under link permissions maybe? Like edit the permissions and make sure non-hardware-active is selected.

**Comment by nsjames** [comment]
I've seen this before actually. Try removing the non-hardware account and re-importing it. I've yet to track down this bug but I'm searching.

**Comment by nsjames** [comment]
Fixed in last release
