### ISSUE TITLE
Polish: Enter to submit forms

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#9]
For example can't press Enter to unlock Scatter after typing in password. I think there was another form i wanted to submit that i also tried completing with Enter instead of trying to press a button and it didn't let me.

Not sure if this might be a Mac only thing.

![image](https://user-images.githubusercontent.com/2923/42550108-ac7cabe2-849d-11e8-91f2-d89935cb4670.png)

**Comment by nsjames** [comment]
Added this for login and create scatter only, it will have to be added manually for each input since there might be multiple options.

If you see more that might need it ticket me and I'll add them.
