### ISSUE TITLE
Signing dapp transactions not working with hardware wallet

### ISSUE THREAD

**Issue by gerakis** [GetScatter/ScatterDesktop#91]
When using scatter to sign dapp transactions, such as https://dice.eosbet.io/, I cant seem to use my hardware wallet to sign transactions. I click roll, a window pops up in scatter asking me to approve or disapprove, I hit approve, then it says "Check Hardware Wallet. Please check your hardware wallet screen." Only there is nothing on my hardware wallet screen. Its just showing the standard EOS options (settings, about, etc) with no request to approve anything. So it becomes impossible to approve anything and I cant play dice. 

This same thing happens with other apps too. I tried voting in eostoolkit.io and the exact same thing happened. No popups to approve on the hardware wallet.

Im using chrome in windows 10 with scatter-9.1.2 with a ledger nano S. I CAN approve of money transfers through the scatter app itself, so that part works fine. The approve prompt appears on the ledger hardware wallet and I click the right button to send the money. Its just the dapps im having trouble with.

When using a non-hardware wallet, like a wallet in the vault thats just stored on my hard drive somewhere, it works fine. I can play dice with no problem. So this seems like something isolated to hardware wallets.

**Comment by nsjames** [comment]
Ledger EOS App doesn't support dapps right now, only system actions like `EOS transfer, delegatebw, etc`. It also doesn't support `updateauth` yet. 

Once those actions are supported they will instantly be supported within Scatter. 

However if I'm not mistaken EOSBet uses a standard transfer action. You might just need to disconnect and reconnect the ledger, which is an issue that is being tracked and worked on.
