### ISSUE TITLE
Issue with password error in settings panels

### ISSUE THREAD

**Issue by nsjames** [GetScatter/ScatterDesktop#97]
From telegram chat

> I went to networks and input an incorrect password by accident and the outcome was a white screen where I was unable to do anything. Following that I had to close Scatter and reopen it but then I found I was unable to login with my correct password. I recovered the situation by restoring my Scatter config from a backup.

**Comment by nsjames** [comment]
I can not reproduce this error. 

Pushing a user out of scatter on a bad password in settings is by design. However the correct password still logs in afterwards.

**Comment by Sceat** [comment]
### SOLVED
by pressing <kbd>d</kbd> `10` time to be able to reset everything
